### PR TITLE
🐛Fix conversion of IdentityRef converting between v1alpha4 and v1beta1

### LINKED ISSUE #1065: IdentityRef is not preserved converting between v1alpha4 and v1beta1
/kind bug

Discovered by unit testing. IdentityRef annotated with `+k8s:conversion-gen=false`, possibly because it was new in v1alpha4 and we wanted to ignore it when converting from v1alpha3. However, we don't want to ignore it when converting to v1beta1, but it is still ignored.

### PR DESCRIPTION
**Pull request by mdbooth**
**What this PR does / why we need it**:
The most interesting parts of this PR are the new unit tests. The tests are little more than a 'do the fields line up' test, but they did highlight that we were missing conversion of IdentityRef.

I will be adding to these tests in #1030

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1065 #1060

### CODE REVIEW

File: api/v1alpha3/conversion_test.go [hunk 1]
```diff
@@ -0,0 +1,259 @@
+/*
+Copyright 2020 The Kubernetes Authors.
```
Comment (hidekazuna) [inline api/v1alpha3/conversion_test.go:2]: 2020 should be 2021.

File: api/v1alpha4/conversion_test.go [hunk 2]
```diff
@@ -0,0 +1,331 @@
+/*
+Copyright 2020 The Kubernetes Authors.
```
Comment (hidekazuna) [inline api/v1alpha4/conversion_test.go:2]: same here.

**Review by hidekazuna — COMMENTED** [review]
Overall lgtm, some nits.

**Comment by tobiasgiese** [comment]
/lgtm
good catch, thanks for the unit tests 👍🏻

**Comment by tobiasgiese** [comment]
@mdbooth what about #1060, shouldn't this fit here too?

**Comment by mdbooth** [comment]
> @mdbooth what about #1060, shouldn't that also fit here?

Looks like it. Also I didn't realise we already had infrastructure for this! Those AWS tests are a whole lot more readable. I'll check out what they do.

**Comment by tobiasgiese** [comment]
+1 for the *new* conversion unit tests, this is really much more readable 👌🏻

**Comment by mdbooth** [comment]
Apart from more readable they're also significantly more thorough! They uncovered some missing pieces of CloudSecret<->IdentityRef conversion which I've hopefully rectified here.

**Comment by iamemilio** [comment]
/lgtm
I love the fuzz tests

**Comment by iamemilio** [comment]
/lgtm
I love the fuzz tests

File: api/v1alpha4/conversion_test.go (hunk 2 above)
Comment (mdbooth) [reply api/v1alpha4/conversion_test.go]: Ditto.

**Comment by jichenjc** [comment]
/approve

thanks for the test cases :)
