### PR TITLE
:bug: Fix Port Leaks

### LINKED ISSUE #1404: CAPO leaks ports if machines can not be created (HTTP 500 NoValidHosts)
/kind bug

**What steps did you take and what happened:**

Running CAPO 0.6.3 (plus a no_volume patch but this may be irrelevant to what we see).
If CAPO tries to create a machine and OpenStack returns an error (can't create VM) in this process, capo will not clean up the ports.
This means if one reaches the "breaking point" of what OpenStack can create, CAPO will leak the ports till one reaches the quota, or some other limit.
Ports never get cleaned up on 500 HTTP error msg on VM creation.

The order of operation:
1. md is configured to some value of machines that OpenStack can't create
2. md is stuck in ScalingUp state
3. OpenStack returns HTTP 500 (no valid hosts)
4. CAPO deletes the machine properly from the OpenStack but leaves the port
5. This causes ports to leak and eventually hit the quota

Here are some logs:

In this case 11 replicas is a "breaking point" for Openstack (it is able to create 10 machines but not the 11th).
This is what kicks in the port leak avalanche

```
➜  ~ kubectl get md
NAME                  CLUSTER          REPLICAS   READY   UPDATED   UNAVAILABLE   PHASE       AGE     VERSION
test-md-0    test    11         10      11        1             ScalingUp   11d     v1.21.3
```

This OpenStack was brought to it's knees by CAPI creating excessive ports:
(10 real active VMs, other are down leaked ports):
```
root@2481423024b3:# openstack port list  | grep test-md-0 | grep DOWN | wc -l
457
root@2481423024b3:/# openstack port list  | grep lab-sjc3-blue-md-0 | grep ACTIVE | wc -l
10
```

osm/ma showing:
```
status:
  failureMessage: 'OpenStack instance cannot be created: error creating Openstack
    instance: error creating OpenStack instance 4c18a354-1b05-403f-b228-b6cd8bdb6452,
    status changed to error'
  failureReason: UpdateError
```
OpenStack showing 500 (before capi deletes the port):

```
| fault                               | {'code': 500, 'created': '2022-11-28T18:26:18Z', 'message': 'No valid host was found. There are not enough hosts available.', 'details':
```

### CAPO logs (one example of one failed VM / leftover port):

```
I1128 18:22:15.237468       1 openstackmachine_controller.go:97] controller/openstackmachine "msg"="Machine Controller has not yet set OwnerRef" "name"="test-md-0-rg6wq" "namespace"="tenant-capi-mgmnt" "openStackMachine"="test-md-0-rg6wq" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackMachine"
I1128 18:22:15.345805       1 openstackmachine_controller.go:97] controller/openstackmachine "msg"="Machine Controller has not yet set OwnerRef" "name"="test-md-0-rg6wq" "namespace"="tenant-capi-mgmnt" "openStackMachine"="test-md-0-rg6wq" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackMachine"
I1128 18:22:15.450520       1 openstackmachine_controller.go:97] controller/openstackmachine "msg"="Machine Controller has not yet set OwnerRef" "name"="test-md-0-rg6wq" "namespace"="tenant-capi-mgmnt" "openStackMachine"="test-md-0-rg6wq" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackMachine"
I1128 18:22:15.498447       1 openstackmachine_controller.go:97] controller/openstackmachine "msg"="Machine Controller has not yet set OwnerRef" "name"="test-md-0-rg6wq" "namespace"="tenant-capi-mgmnt" "openStackMachine"="test-md-0-rg6wq" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackMachine"
I1128 18:22:16.238332       1 openstackmachine_controller.go:293] controller/openstackmachine "msg"="Bootstrap data secret reference is not yet available" "cluster"="test" "machine"="test-md-0-76d989d445-l7hf7" "name"="test-md-0-rg6wq" "namespace"="tenant-capi-mgmnt" "openStackCluster"="test" "openStackMachine"="test-md-0-rg6wq" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackMachine"
I1128 18:22:16.950686       1 openstackmachine_controller.go:293] controller/openstackmachine "msg"="Bootstrap data secret reference is not yet available" "cluster"="test" "machine"="test-md-0-76d989d445-l7hf7" "name"="test-md-0-rg6wq" "namespace"="tenant-capi-mgmnt" "openStackCluster"="test" "openStackMachine"="test-md-0-rg6wq" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackMachine"
I1128 18:22:17.674630       1 openstackmachine_controller.go:300] controller/openstackmachine "msg"="Reconciling Machine" "cluster"="test" "machine"="test-md-0-76d989d445-l7hf7" "name"="test-md-0-rg6wq" "namespace"="tenant-capi-mgmnt" "openStackCluster"="test" "openStackMachine"="test-md-0-rg6wq" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackMachine"
I1128 18:22:17.674670       1 service.go:70] controller/openstackmachine "msg"="failed to create volume service client, no volume related operations allowed" "cluster"="test" "machine"="test-md-0-76d989d445-l7hf7" "name"="test-md-0-rg6wq" "namespace"="tenant-capi-mgmnt" "openStackCluster"="test" "openStackMachine"="test-md-0-rg6wq" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackMachine"
I1128 18:22:18.291380       1 openstackmachine_controller.go:402] controller/openstackmachine "msg"="Machine not exist, Creating Machine" "cluster"="test" "machine"="test-md-0-76d989d445-l7hf7" "name"="test-md-0-rg6wq" "namespace"="tenant-capi-mgmnt" "openStackCluster"="test" "openStackMachine"="test-md-0-rg6wq" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackMachine" "Machine"="test-md-0-rg6wq"
I1128 18:22:20.122215       1 recorder.go:103] events "msg"="Normal"  "message"="Created port test-md-0-rg6wq-0 with id 3fa740bc-d456-486e-8341-830ab036a78f" "object"={"kind":"OpenStackMachine","namespace":"tenant-capi-mgmnt","name":"test-md-0-rg6wq","uid":"ea9a23da-bd7f-4363-94b2-0a97a74431d9","apiVersion":"infrastructure.cluster.x-k8s.io/v1alpha5","resourceVersion":"65612058"} "reason"="Successfulcreateport"
E1128 18:22:32.214637       1 openstackmachine_controller.go:493] controller/openstackmachine "msg"="OpenStack instance cannot be created: error creating Openstack instance: error creating OpenStack instance 34528e59-6c1c-4c6b-aec0-eee89fc40db0, status changed to error" "error"="UpdateError" "cluster"="test" "machine"="test-md-0-76d989d445-l7hf7" "name"="test-md-0-rg6wq" "namespace"="tenant-capi-mgmnt" "openStackCluster"="test" "openStackMachine"="test-md-0-rg6wq" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackMachine"
I1128 18:22:32.214781       1 recorder.go:103] events "msg"="Warning"  "message"="Failed to create server test-md-0-rg6wq: error creating OpenStack instance 34528e59-6c1c-4c6b-aec0-eee89fc40db0, status changed to error" "object"={"kind":"OpenStackMachine","namespace":"tenant-capi-mgmnt","name":"test-md-0-rg6wq","uid":"ea9a23da-bd7f-4363-94b2-0a97a74431d9","apiVersion":"infrastructure.cluster.x-k8s.io/v1alpha5","resourceVersion":"65612058"} "reason"="Failedcreateserver"
E1128 18:22:32.238193       1 controller.go:317] controller/openstackmachine "msg"="Reconciler error" "error"="error creating Openstack instance: error creating OpenStack instance 34528e59-6c1c-4c6b-aec0-eee89fc40db0, status changed to error" "name"="test-md-0-rg6wq" "namespace"="tenant-capi-mgmnt" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackMachine"
I1128 18:22:32.924530       1 openstackmachine_controller.go:275] controller/openstackmachine "msg"="Not reconciling machine in failed state. See openStackMachine.status.failureReason, openStackMachine.status.failureMessage, or previously logged error for details" "cluster"="test" "machine"="test-md-0-76d989d445-l7hf7" "name"="test-md-0-rg6wq" "namespace"="tenant-capi-mgmnt" "openStackCluster"="test" "openStackMachine"="test-md-0-rg6wq" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackMachine"
I1128 18:22:33.638860       1 openstackmachine_controller.go:202] controller/openstackmachine "msg"="Reconciling Machine delete" "cluster"="test" "machine"="test-md-0-76d989d445-l7hf7" "name"="test-md-0-rg6wq" "namespace"="tenant-capi-mgmnt" "openStackCluster"="test" "openStackMachine"="test-md-0-rg6wq" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackMachine"
I1128 18:22:33.638902       1 service.go:70] controller/openstackmachine "msg"="failed to create volume service client, no volume related operations allowed" "cluster"="test" "machine"="test-md-0-76d989d445-l7hf7" "name"="test-md-0-rg6wq" "namespace"="tenant-capi-mgmnt" "openStackCluster"="test" "openStackMachine"="test-md-0-rg6wq" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackMachine"
I1128 18:22:36.153249       1 openstackmachine_controller.go:265] controller/openstackmachine "msg"="Reconciled Machine delete successfully" "cluster"="test" "machine"="test-md-0-76d989d445-l7hf7" "name"="test-md-0-rg6wq" "namespace"="tenant-capi-mgmnt" "openStackCluster"="test" "openStackMachine"="test-md-0-rg6wq" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackMachine"
I1128 18:22:36.153332       1 recorder.go:103] events "msg"="Normal"  "message"="Deleted server test-md-0-rg6wq with id 34528e59-6c1c-4c6b-aec0-eee89fc40db0" "object"={"kind":"OpenStackMachine","namespace":"tenant-capi-mgmnt","name":"test-md-0-rg6wq","uid":"ea9a23da-bd7f-4363-94b2-0a97a74431d9","apiVersion":"infrastructure.cluster.x-k8s.io/v1alpha5","resourceVersion":"65612239"} "reason"="Successfuldeleteserver"
E1128 18:22:36.170527       1 controller.go:317] controller/openstackmachine "msg"="Reconciler error" "error"="openstackmachines.infrastructure.cluster.x-k8s.io \"test-md-0-rg6wq\" not found" "name"="test-md-0-rg6wq" "namespace"="tenant-capi-mgmnt" "reconciler group"="infrastructure.cluster.x-k8s.io" "reconciler kind"="OpenStackMachine"
```

This is not the correct behavior and CAPO should clean up the ports if the ma/osm is in error state.
Cleanup of the VM works, but it seems we would delete  ports only on cluster deletion (or some other err scenarios), but not this one.

**What did you expect to happen:**

In the case of 500 message (or any failure to create VM), corresponding port should be deleted.
It may be that CAPO is looking at the server properties in the vm creation flow, but in the case of 500 err message, there are  not port data to be fetched (looking at the code for this).

**Anything else you would like to add:**

### According to instance.go we do garbage collect the ports.
I would have expected that this would work, as the logs do indicate that we detect `infrav1.InstanceStateError` as the instance state, so I would expect that the garbage collection kicks in here:

https://github.com/anaperic/cluster-api-provider-openstack/blob/0648aa47c0396198cf55aaf23de6e7b39bfa5d82/pkg/cloud/services/compute/instance.go#L580-L581

### One similar issues is fixed but only on cluster delete it seems (not tried)

I did see this issue and a fix, that we did not try yet, but it seems this solves only the cluster delete port deletion.
And here we are talking about port deletion upon unsuccessful VM creation.

https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1254
There was a previous bug for port leak but this is merged back in 2021 and the 0.6.3 should have this fix:

https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/798/files#diff-5e7dbfd52305a21a11fb94fab201062ae2c7b851db93c2a8443a1d82d7aa7936

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built):
(https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1345)

Manually patched (no_volume PR patch) on top of:
```
commit e103e434b851a2a017445cd581de2145a7ee09e9 (origin/release-0.6, release-0.6)
Merge: ecc4cb10 3f35be7a
Author: ji chen <jichenjc@cn.ibm.com>
Date:   Mon Sep 5 15:45:59 2022 +0800

    Merge pull request #1336 from apricote/remove-myself-0.6

    🌱 remove apricote from reviewers
```

- Cluster-API version: 1.2.1
- OpenStack version: xena
- Minikube/KIND version: n/a
- Kubernetes version (use `kubectl version`): 1.21.3
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04.5 LTS

### PR DESCRIPTION
**Pull request by spjmurray**
**What this PR does / why we need it**:

When an instance fails to come up, there's a bug where the port doesn't get cleaned up, and eventually you will exhaust your quota. The code does attempt to garbage collect, but I suspect at some point in the past ports were suffixed with an index, but the garbage collection code wasn't made aware of this, so lists nothing. Replace the APi "filtering" that doesn't work with a manual filter that does prefix matching.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1404

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**TODOs**:

- [ ] squashed commits
- if necessary:
  - [ ] includes documentation
  - [ ] adds unit tests

/hold

### CODE REVIEW

File: pkg/cloud/services/compute/instance.go [hunk 1]
```diff
@@ -380,14 +380,6 @@ func (s *Service) createInstanceImpl(eventObject runtime.Object, openStackCluste
 	return createdInstance, nil
 }
 
-// getPortName appends a suffix to an instance name in order to try and get a unique name per port.
```
Comment (spjmurray) [inline pkg/cloud/services/compute/instance.go:383]: Why did I move this you will inevitably ask?  Well, problem is I want to associate the test with the function that causes the issue in the first place.  Problem is I cannot just export this and include it because of circular dependencies.  That led me to going, well this should be a `networking_test` package anyway, which then led to to not being able to create the networking service due to the client filed not being exported, which then became ugly because of a hacky `NewWithClientForTestOnly()` function in the production code.  Moving it was by far the simplest solution.

File: pkg/cloud/services/networking/port_test.go [hunk 2]
```diff
@@ -535,6 +535,68 @@ func Test_GetOrCreatePort(t *testing.T) {
...
 }
 
+func Test_GarbageCollectErrorInstancesPort(t *testing.T) {
+	mockCtrl := gomock.NewController(t)
+	defer mockCtrl.Finish()
+
+	instanceName := "foo"
+	portID1 := "dc6e0ae3-dad6-4240-a9cb-e541916f20d3"
+	portID2 := "a38ab1cb-c2cc-4c1b-9d1d-696ec73356d2"
+	portName1 := GetPortName(instanceName, nil, 0)
```
Comment (spjmurray) [inline pkg/cloud/services/networking/port_test.go:545]: RE: above comment, I wanted to be absolutely sure that things generated with `GetPortName` will get offed.  By adding a tight coupling between the test and the call, you'll be less likely to change one in a broken way without being drawn to the test cases, so a win in my opinion,

File: pkg/cloud/services/networking/port.go [hunk 3]
```diff
@@ -290,17 +290,32 @@ func (s *Service) DeletePorts(openStackCluster *infrav1.OpenStackCluster) error
...
 
 func (s *Service) GarbageCollectErrorInstancesPort(eventObject runtime.Object, instanceName string) error {
-	portList, err := s.client.ListPort(ports.ListOpts{
-		Name: instanceName,
-	})
+	// NOTE: when creating an instance, ports are named using getPortName(), which
+	// features an index, so we must list all ports and delete those that start with
+	// the instance name.  Specifying the name in the list options will only return
+	// a direct match.
+	portList, err := s.client.ListPort(ports.ListOpts{})
```
Comment (dulek) [inline pkg/cloud/services/networking/port.go:297]: That can be a really long list to go through. Could we reasonably use the API that allows us to filter using multiple name parameters [1]? Feels like not, because we don't know the number of ports, but I'm desperately trying to find something to filter on here.

Or maybe we're able to filter on description? [2] as it's populated with a cluster name [3]?

[1] https://docs.openstack.org/api-ref/network/v2/index.html#filtering-and-column-selection
[2] https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/3d1149683d05af6980c7b745f0f9979d57266e1e/pkg/cloud/services/networking/port.go#L137
[3] https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/3d1149683d05af6980c7b745f0f9979d57266e1e/pkg/cloud/services/networking/port.go#L75-L78

**Review by dulek — CHANGES_REQUESTED** [review]

File: pkg/cloud/services/networking/port.go (hunk 3 above)
Comment (spjmurray) [reply pkg/cloud/services/networking/port.go:297]: Could we infer the number of ports?  Possibly, you can generate the port from the cluster and instance spec...

I think the problem with the description filtering is it _may_ contain the cluster name, looks like you can override this at the spec level 🤷🏻

Comment (dulek) [reply pkg/cloud/services/networking/port.go:297]: Hm, indeed, you're right. Then it feels like generating the expected names from the spec is the safest way to go here, especially as you can override the index using `nameSuffix` [1] Could you see if the code comes out very complicated if that's attempted?

[1] https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/6912766099b348fb520ebc20e167bba72c00fb5d/pkg/cloud/services/compute/instance.go#L384-L386

**Comment by spjmurray** [comment]
@dulek I've probably broken everything, but this may be a "better", definitely far more complex solution, but I can always revert back to the KISS version.

So I've copied instance creation by generating an `InstanceSpec`, propagated that down so we can generate `[]PortOpts` then passed that down to the garbage collector so we only check for specific ports that should exist.

File: pkg/cloud/services/networking/port.go [hunk 4]
```diff
@@ -289,18 +289,34 @@ func (s *Service) DeletePorts(openStackCluster *infrav1.OpenStackCluster) error
...
 		}
+
+		// NOTE: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/issues/1476
+		// It is up to the end user to specify a UNIQUE cluster name when provisioning in the
+		// same project, otherwise things will alias and we could delete more than we should.
+		for _, p := range portList {
+			if err := s.DeletePort(eventObject, p.ID); err != nil {
+				return err
+			}
+		}
```
Comment (dulek) [inline pkg/cloud/services/networking/port.go:310]: We should probably error out if there are multiple ports of that name? Unless we can get to such a case in a single cluster scenario too?

**Review by dulek — CHANGES_REQUESTED** [review]
Honestly I like this version more, thank you! One comment inline.

File: pkg/cloud/services/networking/port.go (hunk 4 above)
Comment (spjmurray) [reply pkg/cloud/services/networking/port.go:310]: Agreed, update incoming.  And now this has been philosophically reviewed, I guess I had better test it!  Luckily I have a 0.8.0 branch... back in a bit.

Comment (spjmurray) [reply pkg/cloud/services/networking/port.go]: Good news!  It does actually work.

File: pkg/cloud/services/networking/port.go [hunk 5]
```diff
@@ -289,18 +289,38 @@ func (s *Service) DeletePorts(openStackCluster *infrav1.OpenStackCluster) error
...
-	for _, p := range portList {
-		if err := s.DeletePort(eventObject, p.ID); err != nil {
+func (s *Service) GarbageCollectErrorInstancesPort(eventObject runtime.Object, instanceName string, portOpts []infrav1.PortOpts) error {
+	for i := range portOpts {
+		portOpt := &portOpts[i]
+
+		portName := GetPortName(instanceName, portOpt, i)
+
+		// TODO: whould be nice if gophercloud could be persuaded to accept multiple
+		// names as is allowed by the API in order to reduce API traffic.
```
Comment (mdbooth) [inline pkg/cloud/services/networking/port.go:299]: ping @pierreprinetti 

If you'd like to resurrect that effort? The use cases are mounting.

**Review by mdbooth — APPROVED** [review]

**Comment by spjmurray** [comment]
@mdbooth thanks!  Should I unhold this or is that your job?  Speaking of which... do we have a rough estimate for 0.8.0 GA?

**Comment by mdbooth** [comment]
@spjmurray You get the pleasure of removing your hold :) Unless I get bored waiting for you, that is, but that takes a couple of weeks.

**Comment by spjmurray** [comment]
Not mine it's part of the PR template.

**Comment by pierreprinetti** [comment]
Here's a proposal for "or" junctions in Gophercloud `List` queries: https://github.com/gophercloud/utils/pull/190
Would this match your use-case?

I would also really appreciate candid feedback on how ergonomic my proposal would be. There are many different ways to add this capability to Gophercloud and this is just one of them.
