### PR TITLE
Fix delete pool lead to panic

### LINKED ISSUE #429: error in delete cluster with LB
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

when delete a cluster with following command (has LB created), got panic:

/usr/local/go/src/runtime/asm_amd64.s:1337
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb0 pc=0x10435a0]

goroutine 152 [running]:
sigs.k8s.io/cluster-api-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/src/sigs.k8s.io/cluster-api-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x105
panic(0x1301540, 0x2328050)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
sigs.k8s.io/cluster-api-provider-openstack/pkg/cloud/openstack/services/networking.(*Service).DeleteLoadBalancerMember(0xc00000e688, 0xc000043760, 0xd, 0xc000102000, 0xc0006dc5a0, 0x0, 0x0)
        /go/src/sigs.k8s.io/cluster-api-provider-openstack/pkg/cloud/openstack/services/networking/loadbalancer.go:299 +0x330
sigs.k8s.io/cluster-api-provider-openstack/pkg/cloud/openstack/machine.(*Actuator).Delete(0xc000531e30, 0x1689fe0, 0xc00009e020, 0xc0000cf040, 0xc000102000, 0x1, 0x1)
        /go/src/sigs.k8s.io/cluster-api-provider-openstack/pkg/cloud/openstack/machine/actuator.go:231 +0x873
sigs.k8s.io/cluster-api-provider-openstack/vendor/sigs.k8s.io/cluster-api/pkg/controller/machine.(*ReconcileMachine).Reconcile(0xc000424500, 0xc00009f9e0, 0x7, 0xc000429be0, 0x16, 0x233c140, 0x43c73d, 0xc0002e7df8, 0x1)
        /go/src/sigs.k8s.io/cluster-api-provider-openstack/vendor/sigs.k8s.io/cluster-api/pkg/controller/machine/machine_controller.go:173 +0xe33
sigs.k8s.io/cluster-api-provider-openstack/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0000c6140, 0x0)
        /go/src/sigs.k8s.io/cluster-api-provider-openstack/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215 +0x1cc
sigs.k8s.io/cluster-api-provider-openstack/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1()
        /go/src/sigs.k8s.io/cluster-api-provider-openstack/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158 +0x36
sigs.k8s.io/cluster-api-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00029c5e0)
        /go/src/sigs.k8s.io/cluster-api-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
sigs.k8s.io/cluster-api-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00029c5e0, 0x3b9aca00, 0x0, 0x1, 0xc000048120)
        /go/src/sigs.k8s.io/cluster-api-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xf8
sigs.k8s.io/cluster-api-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc00029c5e0, 0x3b9aca00, 0xc000048120)
        /go/src/sigs.k8s.io/cluster-api-provider-openstack/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/cluster-api-provider-openstack/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
        /go/src/sigs.k8s.io/cluster-api-provider-openstack/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:157 +0x311

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by jichenjc**
1) seems we don't need port 22, have no idea why use here
2) when pool not exist, should check and ignore following actions

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #429 

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

File: pkg/cloud/openstack/services/networking/loadbalancer.go [hunk 1]
```diff
@@ -274,14 +274,18 @@ func (s *Service) DeleteLoadBalancerMember(clusterName string, machine *clusterv
 
 	lbID := clusterProviderStatus.Network.APIServerLoadBalancer.ID
 
-	for _, port := range []int{22, 6443} {
+	for _, port := range []int{6443} {
```
Comment (hidekazuna) [inline pkg/cloud/openstack/services/networking/loadbalancer.go]: When we create the listener and pool, we are doing like:
```Go
portList := []int{clusterProviderSpec.APIServerLoadBalancerPort}
portList = append(portList, clusterProviderSpec.APIServerLoadBalancerAdditionalPorts...)
for _, port := range portList {
        lbPortObjectsName := fmt.Sprintf("%s-%d", loadBalancerName, port)
```
Please refer to https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/pkg/cloud/openstack/services/networking/loadbalancer.go#L84-L86

Comment (sbueringer) [reply pkg/cloud/openstack/services/networking/loadbalancer.go]: Oh sorry, I though I already fixed that somewhere.

So the solution is to remove the same list of ports that have been added before
