### PR TITLE
🐛 Better checks before creating Floating IPs

### LINKED ISSUE #2260: panic when setting disableExternalNetwork: true
/kind bug

**What steps did you take and what happened:**
I create a openstackcluster like this :
```
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackCluster
metadata:
  name: foo
  namespace: foo-cluster
spec:
  identityRef:
    cloudName: idf1
    name: clouds.idf1.opp
  managedSubnets:
  - cidr: 192.168.100.0/24
  disableExternalNetwork: true
```
And this happen in the 'capo-controller-manager' :
```
I1119 10:29:16.598608       1 controller.go:110] "Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference" controller="openstackcluster" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="OpenStackCluster" OpenStackCluster="foo-cluster/foo" namespace="foo-cluster" name="foo" reconcileID="29b6c15b-d500-4fc8-8a1f-d56223a4e226"
panic: runtime error: invalid memory address or nil pointer dereference [recovered]                                                                                                                panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1b774f9]

goroutine 357 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()                                                                                                             /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.5/pkg/internal/controller/controller.go:111 +0x1e5
panic({0x1dccbe0?, 0x362a670?})
        /usr/local/go/src/runtime/panic.go:770 +0x132
sigs.k8s.io/cluster-api-provider-openstack/pkg/cloud/services/networking.(*Service).GetOrCreateFloatingIP(0xc000392bd0, {0x242a030, 0xc0004a4588}, 0x1cce7a0?, {0xc000a72680?, 0x1cce7a0?}, 0xc000afcae0?)
        /workspace/pkg/cloud/services/networking/floatingip.go:53 +0xf9
sigs.k8s.io/cluster-api-provider-openstack/controllers.reconcileControlPlaneEndpoint(0xc000392bd0?, 0xc0004a4588?, 0xc0004a4588, {0xc000a72680?, 0x1e?})
        /workspace/controllers/openstackcluster_controller.go:804 +0x290
sigs.k8s.io/cluster-api-provider-openstack/controllers.reconcileNetworkComponents(0xc000b00db0, 0xc0005fc000, 0xc0004a4588)
        /workspace/controllers/openstackcluster_controller.go:685 +0x428
sigs.k8s.io/cluster-api-provider-openstack/controllers.(*OpenStackClusterReconciler).reconcileNormal(0xc0003e5ec0, {0x2440510, 0xc00076e660}, 0xc000b00db0, 0xc0005fc000, 0xc0004a4588)
        /workspace/controllers/openstackcluster_controller.go:312 +0xf2
sigs.k8s.io/cluster-api-provider-openstack/controllers.(*OpenStackClusterReconciler).Reconcile(0xc0003e5ec0, {0x2440510, 0xc00076e660}, {{{0xc0008049f0?, 0x0?}, {0xc0008049ec?, 0xc0002a5d10?}}})
        /workspace/controllers/openstackcluster_controller.go:135 +0x6d0
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x2446788?, {0x2440510?, 0xc00076e660?}, {{{0xc0008049f0?, 0xb?}, {0xc0008049ec?, 0x0?}}})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.5/pkg/internal/controller/controller.go:114 +0xb7
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0001668f0, {0x2440548, 0xc0005f8b90}, {0x1e96420, 0xc000386680})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.5/pkg/internal/controller/controller.go:311 +0x3bc
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0001668f0, {0x2440548, 0xc0005f8b90})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.5/pkg/internal/controller/controller.go:261 +0x1be
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()                                                                                                               /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.5/pkg/internal/controller/controller.go:222 +0x79
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2 in goroutine 184
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.5/pkg/internal/controller/controller.go:218 +0x486
```

**What did you expect to happen:**
No panic in the controller.

**Anything else you would like to add:**
i think it's due to this [https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/7800252fc6e2adc60e2b40633adbcbb89be9da51/pkg/cloud/services/networking/floatingip.go#L53](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/7800252fc6e2adc60e2b40633adbcbb89be9da51/pkg/cloud/services/networking/floatingip.go#L53)
Go try to get the id of the externalnetwork, but externalnetwork is disabled

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): 0.11.2
- Cluster-API version: 1.8.4
- OpenStack version: yoga
- Minikube/KIND version: NA
- Kubernetes version (use `kubectl version`): 1.31
- OS (e.g. from `/etc/os-release`): talos

### PR DESCRIPTION
**Pull request by EmilienM**
**What this PR does / why we need it**:

When a floating is created, we need to make sure that
`OpenStackCluster.Spec.DisableExternalNetwork` is not set to `True`.
Otherwise, we'll have a nil pointer error.

* Add a check in `reconcileBastion` to check that external network is
  not disabled before creating the floating IP for the bastion.
* Add a check in `reconcileControlPlaneEndpoint` and
  `reconcileAPIServerLoadBalancer` to check that external
  network is not disabled (alongside the DisableAPIServerFloatingIP
  check) before creating the floating IP for the API server endpoint.
* Add a safeguard in `GetOrCreateFloatingIP` to return a proper error
  (instead of a nil pointer error) when
  `openStackCluster.Status.ExternalNetwork` is nil.
* Add API CEL to check that when DisableExternalNetwork is set and true,
  the bastion (if defined) doesn't have a floating IP defined and also
  that disableAPIServerFloatingIP (when set) is not False.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2260

### CODE REVIEW

**Comment by EmilienM** [comment]
I initially wanted to do some webhook to just disallow `DisableExternalNetwork` to be True without also setting `DisableAPIServerFloatingIP` to True but it's not backward compatible and sucks for our users, so I did that.

**Review by mdbooth — COMMENTED** [review]
/lgtm

Any idea how far back we need to backport this? 0.11 at least.

**Comment by EmilienM** [comment]
> /lgtm
> 
> Any idea how far back we need to backport this? 0.11 at least.

I'll investigate.

**Comment by EmilienM** [comment]
On this one I want an eye from @lentzi90.

File: controllers/openstackcluster_controller.go [hunk 1]
```diff
@@ -395,7 +395,11 @@ func (r *OpenStackClusterReconciler) reconcileBastion(ctx context.Context, scope
 		return nil, err
 	}
 
-	return bastionAddFloatingIP(openStackCluster, clusterResourceName, port, networkingService)
+	if !ptr.Deref(openStackCluster.Spec.DisableExternalNetwork, false) {
+		return bastionAddFloatingIP(openStackCluster, clusterResourceName, port, networkingService)
+	}
+
+	return nil, nil
```
Comment (lentzi90) [inline controllers/openstackcluster_controller.go:402]: What do you think about doing this the other way? If disabled -> log something and return. Otherwise continue and add it.

**Review by lentzi90 — COMMENTED** [review]
> I initially wanted to do some webhook to just disallow DisableExternalNetwork to be True without also setting DisableAPIServerFloatingIP to True but it's not backward compatible and sucks for our users

Sure not backwards compatible, but do you mean that it is actually possible to use that configuration? I'm thinking it is ok to break backwards compatibility if all it was doing was cause nil pointer exceptions.

File: controllers/openstackcluster_controller.go (hunk 1 above)
Comment (EmilienM) [reply controllers/openstackcluster_controller.go:402]: IIUC what you're proposing is

```golang
...
if ptr.Deref(openStackCluster.Spec.DisableExternalNetwork, false) {
        // log something? what exactly?
	return nil, nil
}
return bastionAddFloatingIP(openStackCluster, clusterResourceName, port, networkingService)
```

If yes, I think it's functionally the same and is fairly consistent with other Deref calls for that field. No strong opinion here, happy to make the change.

**Review by lentzi90 — COMMENTED** [review]
/lgtm
Looks good, and no need for extra logging now that the webhook immediately tells the user what is wrong :slightly_smiling_face:

**Review by lentzi90 — COMMENTED** [review]
I'm happy with this, but as mentioned on slack, I have one concern.
Sorry I didn't think of it earlier.

Will the user ever be the one setting the floating IP? Or are we now just going to block the controller trying to add it?

**Review by lentzi90 — COMMENTED** [review]
Works as expected. If I try to manually do some invalid combination of `disableExternalNetwork` + API server floating IP or bastion floating IP, CEL will block it. If I enable the bastion and disable the external network it will be created without floating IP, no errors in the logs. For this situation there isn't anything obvious telling the user *why* the bastion didn't get a floating IP. That is not ideal, but surely better than nil pointer exceptions, so
/lgtm

**Comment by EmilienM** [comment]
> Works as expected. If I try to manually do some invalid combination of `disableExternalNetwork` + API server floating IP or bastion floating IP, CEL will block it. If I enable the bastion and disable the external network it will be created without floating IP, no errors in the logs. For this situation there isn't anything obvious telling the user _why_ the bastion didn't get a floating IP. That is not ideal, but surely better than nil pointer exceptions, so /lgtm

yeah that's why I updated the doc.

Let's ship it.
/approve
