### PR TITLE
🐛 do not propagate the cloud field to clientconfig.AuthOptions

### LINKED ISSUE #825: unable to load clouds.yaml
/kind bug

**What steps did you take and what happened:**
I've tried to perform steps from [Cluster API Quick Start](https://cluster-api.sigs.k8s.io/user/quick-start.html) in order to create test k8s cluster in our 'on-premise' OpenStack, but faced with an issue after applying cluster manifest.
Cluster has stuck on _Provisioning_ phase, machine resources has stuck in _WaitingForInfrastructure_ state.
```sh
# kubectl get cluster --all-namespaces
NAMESPACE   NAME              PHASE
default     capi-quickstart   Provisioning

# kubectl get kubeadmcontrolplane --all-namespaces
NAMESPACE   NAME                            INITIALIZED   API SERVER AVAILABLE   VERSION    REPLICAS   READY   UPDATED   UNAVAILABLE
default     capi-quickstart-control-plane                                        v1.18.16

# clusterctl describe cluster capi-quickstart --disable-grouping --disable-no-echo 
NAME                                                                         READY  SEVERITY  REASON                           SINCE  MESSAGE
/capi-quickstart                                                             False  Info      WaitingForControlPlane           5m19s
├─ClusterInfrastructure - OpenStackCluster/capi-quickstart
├─ControlPlane - KubeadmControlPlane/capi-quickstart-control-plane
└─Workers
  └─MachineDeployment/capi-quickstart-md-0
    ├─Machine/capi-quickstart-md-0-55fd7d7567-22h5r                          False  Info      WaitingForInfrastructure         5m18s  0 of 2 completed
    │ ├─BootstrapConfig - KubeadmConfig/capi-quickstart-md-0-qbggm           False  Info      WaitingForClusterInfrastructure  5m19s
    │ └─MachineInfrastructure - OpenStackMachine/capi-quickstart-md-0-x4f8g
    ├─Machine/capi-quickstart-md-0-55fd7d7567-7zshr                          False  Info      WaitingForInfrastructure         5m18s  0 of 2 completed
    │ ├─BootstrapConfig - KubeadmConfig/capi-quickstart-md-0-7l4mx           False  Info      WaitingForClusterInfrastructure  5m18s
    │ └─MachineInfrastructure - OpenStackMachine/capi-quickstart-md-0-5tcg2
    └─Machine/capi-quickstart-md-0-55fd7d7567-nrl9f                          False  Info      WaitingForInfrastructure         5m18s  0 of 2 completed
      ├─BootstrapConfig - KubeadmConfig/capi-quickstart-md-0-qpjqh           False  Info      WaitingForClusterInfrastructure  5m19s
      └─MachineInfrastructure - OpenStackMachine/capi-quickstart-md-0-9lvpz
```

Pod _capo-controller-manager_ reports that it unable to load _clouds.yaml_ 
```sh
E0401 12:58:22.237151       1 controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="auth option failed for cloud pilotcloud: unable to load clouds.yaml: no clouds.yaml file found" "controller"="openstackcluster" "name"="capi-quickstart" "namespace"="default"
I0401 12:58:22.237283       1 openstackmachine_controller.go:340] controllers/OpenStackMachine "msg"="Cluster infrastructure is not ready yet, requeuing machine" "cluster"="capi-quickstart" "machine"="capi-quickstart-md-0-55fd7d7567-7zshr" "namespace"="default" "openStackCluster"="capi-quickstart" "openStackMachine"="capi-quickstart-md-0-5tcg2"
I0401 12:58:30.404497       1 openstackmachine_controller.go:340] controllers/OpenStackMachine "msg"="Cluster infrastructure is not ready yet, requeuing machine" "cluster"="capi-quickstart" "machine"="capi-quickstart-md-0-55fd7d7567-7zshr" "namespace"="default" "openStackCluster"="capi-quickstart" "openStackMachine"="capi-quickstart-md-0-5tcg2"
I0401 12:58:30.405240       1 openstackmachine_controller.go:340] controllers/OpenStackMachine "msg"="Cluster infrastructure is not ready yet, requeuing machine" "cluster"="capi-quickstart" "machine"="capi-quickstart-md-0-55fd7d7567-22h5r" "namespace"="default" "openStackCluster"="capi-quickstart" "openStackMachine"="capi-quickstart-md-0-x4f8g"
I0401 12:58:30.768171       1 openstackmachine_controller.go:340] controllers/OpenStackMachine "msg"="Cluster infrastructure is not ready yet, requeuing machine" "cluster"="capi-quickstart" "machine"="capi-quickstart-md-0-55fd7d7567-nrl9f" "namespace"="default" "openStackCluster"="capi-quickstart" "openStackMachine"="capi-quickstart-md-0-9lvpz"
```
But at the same time secret _capi-quickstart-cloud-config_ exists and contains _clouds.yaml_ inside
```sh
# kc get secret capi-quickstart-cloud-config -n default -o yaml | grep ' clouds.yaml'
  clouds.yaml: Y2x<base64-string>ECg==
```

Also this base64 string could be successfully decoded
```sh
# echo 'Y2x<base64-string>ECg==' | base64 -d
clouds:
  pilotcloud:
    cloud: pilotcloud
    region_name: RegionOne
    interface: public
    user_domain_name: Default
    project_domain_name: default
    key: /root/envs/pilotcloud/signing_key.pem
    cert: /root/envs/pilotcloud/signing_cert.pem
    cacert: /root/envs/pilotcloud/ca.pem
    auth:
      auth_url: https://pilotcloud:55000/v3/
      username: <username>
      password: <password>
      project_name: TEST_TENANT
```

**What did you expect to happen:**
Provider will try to connect to OpenStack at least.

**Anything else you would like to add:**
-

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): v0.3.4
- Cluster-API version: v1.13.15
- OpenStack version: -
- KIND version: v0.10.0
- Kubernetes version (use `kubectl version`): Client Version: v1.19.1; Server Version: v1.20.2
- OS (e.g. from `/etc/os-release`): CentOS Linux 7.8

### PR DESCRIPTION
**Pull request by sbueringer**
**What this PR does / why we need it**:

This PR stops propagating the `cloud` field to `clientconfig.AuthOptions`. If this field is actually set, we hit a branch in `AuthOptions` which always fails: (I don't think we have to validate that the field is not set, when we can just change the code that it doesn't matter if it is set or not)

https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/31df024b3205232c3545631afb5027f1f0a3f213/pkg/cloud/services/provider/provider.go#L80-L91

https://github.com/gophercloud/utils/blob/7b186010c04f90ca48b5ce471a222911ff076e00/openstack/clientconfig/requests.go#L352-L370

https://github.com/gophercloud/utils/blob/7b186010c04f90ca48b5ce471a222911ff076e00/openstack/clientconfig/requests.go#L192

https://github.com/gophercloud/utils/blob/7b186010c04f90ca48b5ce471a222911ff076e00/openstack/clientconfig/requests.go#L119

there's not cloud.yaml there which could be found...

Alternative would be to duplicate the code from `AuthOptions` we actually want, but I wouldn't like to maintain that much code on our side:

https://github.com/gophercloud/utils/blob/7b186010c04f90ca48b5ce471a222911ff076e00/openstack/clientconfig/requests.go#L390-L396

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #825

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**TODOs**:

- [x] squashed commits
- if necessary:
  - [x] includes documentation
  - [x] adds unit tests

/hold

### CODE REVIEW

**Comment by sbueringer** [comment]
/assign @blencoff
/assign @jichenjc 

WDYT?

File: pkg/cloud/services/provider/provider.go [hunk 1]
```diff
@@ -80,7 +80,6 @@ func NewClient(cloud clientconfig.Cloud, caCert []byte) (*gophercloud.ProviderCl
 	if cloud.AuthInfo != nil {
 		clientOpts.AuthInfo = cloud.AuthInfo
 		clientOpts.AuthType = cloud.AuthType
-		clientOpts.Cloud = cloud.Cloud
```
Comment (jichenjc) [inline pkg/cloud/services/provider/provider.go:83]: what about a clouds.yaml contains multiple cloud ?

Comment (sbueringer) [reply pkg/cloud/services/provider/provider.go:83]: I assume this does not matter. This is already handled in: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/829/files#diff-dbf706fca1006fa16e85a98f355508c0891e685f846ff079d5ac1d6e6b308148L155

We're only passing one cloud (clientconfig.Cloud) into the NewClient func.

Comment (sbueringer) [reply pkg/cloud/services/provider/provider.go:83]: Also the code path in AuthOptions never works when we set the cloud to a non empty string, because it always searches for a cloud.yaml file at the default locations which we don't have.

Comment (sbueringer) [reply pkg/cloud/services/provider/provider.go:83]: @jichenjc wdyt, okay to merge?

Comment (jichenjc) [reply pkg/cloud/services/provider/provider.go:83]: give me another day, I want to read it more (run out of time today)

Comment (sbueringer) [reply pkg/cloud/services/provider/provider.go:83]: No problem, thx ;)

Comment (jichenjc) [reply pkg/cloud/services/provider/provider.go:83]: we have a set of logics at line 52 / 70 above , such as 
`cloud, caCert, err = getCloudFromSecret(ctrlClient, namespace, openStackCluster.Spec.CloudsSecret.Name, openStackCluster.Spec.CloudName)`

so basically, we are providing info based on cluster.Spec.CloudName

if we don't want to honor this field, should we consider remove 
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/api/v1alpha3/openstackcluster_types.go#L38? 

actually we created a secret and this secret is a clouds.yaml and it might contains multiple clouds
I also think we don't want to (technically ?) support 1 CAPI + multiple openstack solution ? 
if that's the case, maybe we need reconsider adjust the whole `Cloud` related items and manage expecations of users

Comment (sbueringer) [reply pkg/cloud/services/provider/provider.go:83]: Hm I we are using the CloudName here:
* https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/829/files#diff-dbf706fca1006fa16e85a98f355508c0891e685f846ff079d5ac1d6e6b308148R150-R154

We are even checking that it's not empty here:
* https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/829/files#diff-dbf706fca1006fa16e85a98f355508c0891e685f846ff079d5ac1d6e6b308148R125-R127

So in my opinion we need the property and it does exactly what we want. It picks the right cloud if we have multiple in the cloud.yaml. The only problem is that we don't need it in `clientconfig.AuthOptions`. `clientconfig.AuthOptions` is not the func which parses the cloud.yaml so it doesn't need the cloud. 

I don\t really understand what you mean, but we cannot drop the property. We need it, just not here.

Comment (sbueringer) [reply pkg/cloud/services/provider/provider.go:83]: (Also cloud.Cloud is not the **same** as the cloudName in our spec)

Comment (jichenjc) [reply pkg/cloud/services/provider/provider.go:83]: ok, you are right, I was confused by cloud and cloudName variable at first then I misunderstand the logic 
after further read I think you are right , sorry for the confusion

Comment (sbueringer) [reply pkg/cloud/services/provider/provider.go:83]: No problem, it's confusing :). I also would like to use not that much of the AuthOptions func unfortunately the only way to do this is to copy it :/
