### PR TITLE
Document running CI devstack on CentOS

### LINKED ISSUE #1109: CI tests failing due to missing ubuntu-2004-lts in us-east4-a
/kind bug

Error can be seen in build log:

```
+ gcloud compute disks describe capo-e2e-disk --project gce-up-g1-4-clat-up-clu --zone us-east4-a
ERROR: (gcloud.compute.disks.describe) HTTPError 404: The resource 'projects/gce-up-g1-4-clat-up-clu/zones/us-east4-a/disks/capo-e2e-disk' was not found
+ gcloud compute disks create capo-e2e-disk --project gce-up-g1-4-clat-up-clu --image-project ubuntu-os-cloud --image-family ubuntu-2004-lts --zone us-east4-a
ERROR: (gcloud.compute.disks.create) Could not fetch resource:
 - The resource 'projects/ubuntu-os-cloud/zones/us-east4-a/imageFamilyViews/ubuntu-2004-lts' was not found
```

e.g.:
* https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-openstack/1107/pull-cluster-api-provider-openstack-e2e-test/1480893933666963456
* https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-openstack/1095/pull-cluster-api-provider-openstack-e2e-test/1480848100384837632
* https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-openstack/1030/pull-cluster-api-provider-openstack-e2e-test/1480895389681848320

The issue appears to be that ubuntu-2004-lts is not current available in us-east4-a. It exists:

```
$ gcloud compute images describe-from-family ubuntu-2004-lts --project ubuntu-os-cloud                                                                                                                                         archiveSizeBytes: '2656539840'                                                                                                                                                                                                                             creationTimestamp: '2022-01-10T14:16:42.058-08:00'                                                                                                                                                                                                         description: Canonical, Ubuntu, 20.04 LTS, amd64 focal image built on 2022-01-10
...
```

just not in us-east4-a:

```
$ gcloud compute images describe-from-family ubuntu-2004-lts --project ubuntu-os-cloud --zone us-east4-a
ERROR: (gcloud.compute.images.describe-from-family) Could not fetch resource:
 - The resource 'projects/ubuntu-os-cloud/zones/us-east4-a/imageFamilyViews/ubuntu-2004-lts' was not found
```

### PR DESCRIPTION
**Pull request by mdbooth**
#1109 pointed out that it's useful to have an alternative OS option, albeit for a reason I didn't think of when I originally made it possible to use CentOS in addition to Ubuntu. This simply documents the alternative and encourages developers to keep the option open.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1109 

/hold

### CODE REVIEW

File: hack/ci/gce-project.sh [hunk 1]
```diff
@@ -96,7 +96,7 @@ function create_vm {
   then
     gcloud compute disks create "$diskname" \
       --project "$GCP_PROJECT" \
-      --image-project ubuntu-os-cloud --image-family ubuntu-2004-lts \
+      --image-project centos-cloud --image-family centos-stream-8 \
```
Comment (jichenjc) [inline hack/ci/gce-project.sh:99]: it works again today

as alternative, maybe we can try ubuntu first and if it failed, then let's switch to centos
how about add variable so that we can switch easily ?

Comment (mdbooth) [reply hack/ci/gce-project.sh:99]: I think a variable would be a similar effort to update. An advantage of having it hard-coded is also that there's no expectation that anybody is testing the alternative, so it's more obvious you might be expected to fix things.

I'm happy that this is currently working and a potential option for the future.

**Comment by mdbooth** [comment]
The infra issue with Ubuntu images resolved itself, so we don't need this.

**Comment by jichenjc** [comment]
@mdbooth do you think it's worthy to put some doc in our dev doc 
so that someone might fix this by referring to this issue even both of us are absent :)

**Comment by mdbooth** [comment]
> @mdbooth do you think it's worthy to put some doc in our dev doc so that someone might fix this by referring to this issue even both of us are absent :) and suffer same issue in the future?

Good idea. I suspect a simple comment would be most productive, tbh. I'll knock something up.

**Comment by mdbooth** [comment]
@jichenjc How's that?

**Comment by iamemilio** [comment]
+1 from me, but I'll wait for more opinions to trickle in

**Comment by jichenjc** [comment]
/approve

great :) thanks a lot @mdbooth

**Comment by mdbooth** [comment]
/hold cancel

But I think I still need an /lgtm

**Comment by tobiasgiese** [comment]
/lgtm

thanks for improving our dev docs. I think we can only get better 👍🏻
