### PR TITLE
🐛 fix: watch ipaddressclaim in openstackserver controller

### LINKED ISSUE #2389: OpenstackServer controller is not watching IPAdressClaim resources
/kind bug

**What steps did you take and what happened:**
When using an OpenstackFloatingIPPools in an OpenstackMachine, an IPAddressClaim is created which will create a floating ip in Openstack.
However currently the OpenstackServer controller do not watch the IPAddressClaims it create, which stuck the provision of the server.

Here an extract of logs showing that the OpenstackServer is not reconciled until I manually add an annotation on it at 10:01
```
I0123 09:45:06.510424       1 openstackserver_controller.go:100] "Reconciling OpenStackServer" controller="openstackserver" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="OpenStackServer" OpenStackServer="test/test-42kj7-wv56c" namespace="test" name="test-42kj7-wv56c" reconcileID="781a17c3-0a12-462a-bf69-49d9090db489"
I0123 09:45:06.510522       1 openstackserver_controller.go:292] "Reconciling Server create" controller="openstackserver" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="OpenStackServer" OpenStackServer="test/test-42kj7-wv56c" namespace="test" name="test-42kj7-wv56c" reconcileID="781a17c3-0a12-462a-bf69-49d9090db489"
I0123 09:45:06.590125       1 openstackserver_controller.go:623] "Created IPAddressClaim" controller="openstackserver" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="OpenStackServer" OpenStackServer="test/test-42kj7-wv56c" namespace="test" reconcileID="781a17c3-0a12-462a-bf69-49d9090db489" name="test-42kj7-wv56c-floating-ip-address"
I0123 09:45:06.590223       1 recorder.go:104] "Creating IPAddressClaim test/test-42kj7-wv56c-floating-ip-address" logger="events" type="Normal" object={"kind":"OpenStackServer","namespace":"test","name":"test-42kj7-wv56c","uid":"f83584ad-9a76-479e-9751-3025f64b4c52","apiVersion":"infrastructure.cluster.x-k8s.io/v1alpha1","resourceVersion":"193478720"} reason="CreatingIPAddressClaim"
I0123 09:45:06.590237       1 recorder.go:104] "Waiting for IPAddressClaim test/test-42kj7-wv56c-floating-ip-address to be allocated" logger="events" type="Normal" object={"kind":"OpenStackServer","namespace":"test","name":"test-42kj7-wv56c","uid":"f83584ad-9a76-479e-9751-3025f64b4c52","apiVersion":"infrastructure.cluster.x-k8s.io/v1alpha1","resourceVersion":"193478720"} reason="WaitingForIPAddressClaim"
I0123 09:45:06.941529       1 openstackserver_controller.go:100] "Reconciling OpenStackServer" controller="openstackserver" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="OpenStackServer" OpenStackServer="test/test-42kj7-wv56c" namespace="test" name="test-42kj7-wv56c" reconcileID="2e06b861-a13e-44b9-b0d6-a1197eda26c4"
I0123 09:45:06.941640       1 openstackserver_controller.go:292] "Reconciling Server create" controller="openstackserver" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="OpenStackServer" OpenStackServer="test/test-42kj7-wv56c" namespace="test" name="test-42kj7-wv56c" reconcileID="2e06b861-a13e-44b9-b0d6-a1197eda26c4"
I0123 09:45:07.010089       1 recorder.go:104] "Waiting for IPAddressClaim test/test-42kj7-wv56c-floating-ip-address to be allocated" logger="events" type="Normal" object={"kind":"OpenStackServer","namespace":"test","name":"test-42kj7-wv56c","uid":"f83584ad-9a76-479e-9751-3025f64b4c52","apiVersion":"infrastructure.cluster.x-k8s.io/v1alpha1","resourceVersion":"193478824"} reason="WaitingForIPAddressClaim"
I0123 10:01:04.256450       1 openstackserver_controller.go:100] "Reconciling OpenStackServer" controller="openstackserver" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="OpenStackServer" OpenStackServer="test/test-42kj7-wv56c" namespace="test" name="test-42kj7-wv56c" reconcileID="ff7c8fd1-2bd7-4cf2-b8f6-ec7bd48b1c63"
I0123 10:01:04.256541       1 openstackserver_controller.go:292] "Reconciling Server create" controller="openstackserver" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="OpenStackServer" OpenStackServer="test/test-42kj7-wv56c" namespace="test" name="test-42kj7-wv56c" reconcileID="ff7c8fd1-2bd7-4cf2-b8f6-ec7bd48b1c63"
```

**What did you expect to happen:**
Reconcile the OpenstackServer when the IPAddressClaim is ready.

**Anything else you would like to add:**
I'm new to the OpenSource world, so do not hesitate to correct me.
I already tested a fix: https://github.com/MisterKind/cluster-api-provider-openstack/commit/5519450a5ee1f9e93fb9d3619468d6573d696c09

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): 0.11.4
- Cluster-API version: 1.8.5
- OpenStack version:
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by MisterKind**
**What this PR does / why we need it**:
Add watch of IPAddressClaims in the OpenstackServer controller

**Which issue(s) this PR fixes** :
Fixes #2389

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**TODOs**:

- [X] squashed commits

/hold

### CODE REVIEW

**Comment by EmilienM** [comment]
I think you'll need to run `make generate` in order to generate new RBAC in the CRDs.

File: controllers/openstackserver_controller.go [hunk 1]
```diff
@@ -214,6 +216,10 @@ func (r *OpenStackServerReconciler) SetupWithManager(ctx context.Context, mgr ct
 			}),
 			builder.WithPredicates(predicates.NewBecameAvailable(mgr.GetLogger(), &orcv1alpha1.Image{})),
 		).
+		Watches(
+			&ipamv1.IPAddressClaim{},
+			handler.EnqueueRequestForOwner(mgr.GetScheme(), mgr.GetRESTMapper(), &infrav1alpha1.OpenStackServer{}),
```
Comment (EmilienM) [inline controllers/openstackserver_controller.go:221]: I know it's a copy paste from the openstackmachine controller but I wonder if we would want a predicate at some point, to ensure we trigger the create only when the FIP is created.

File: controllers/openstackserver_controller.go [hunk 2]
```diff
@@ -77,6 +77,8 @@ type OpenStackServerReconciler struct {
 
 // +kubebuilder:rbac:groups=infrastructure.cluster.x-k8s.io,resources=openstackservers,verbs=get;list;watch;create;update;patch;delete
 // +kubebuilder:rbac:groups=infrastructure.cluster.x-k8s.io,resources=openstackservers/status,verbs=get;update;patch
+// +kubebuilder:rbac:groups=ipam.cluster.x-k8s.io,resources=ipaddressclaims;ipaddressclaims/status,verbs=get;watch;create;update;patch;delete
+// +kubebuilder:rbac:groups=ipam.cluster.x-k8s.io,resources=ipaddresses;ipaddresses/status,verbs=get;list;watch
```
Comment (EmilienM) [inline controllers/openstackserver_controller.go:81]: @mdbooth @lentzi90 I'll use a second pair of eyes here, as I'm not 100% we want a copy/paste from the OpenStackMachine controller. I thought that ipaddressclaim would be enough but I don't know enough that resource. I can dig into it next week (at this point) if you don't know either.

**Review by EmilienM — COMMENTED** [review]
Thanks for your first contribution, it's very appreciated. It touches an area where I'm not 100% comfortable (the FIP resource) with so I pinged Matt and Lennart. If you don't hear from us by mid next week, please let me know. I think it's an important bug to fix.

Also we'll need it backported.

**Comment by MisterKind** [comment]
> I think you'll need to run `make generate` in order to generate new RBAC in the CRDs.

I already did it, but as the RBAC are the same as the OpenstackMachine controller, there no modifications.

File: controllers/openstackserver_controller.go (hunk 2 above)
Comment (MisterKind) [reply controllers/openstackserver_controller.go:81]: We need both for the OpenstackServer controller, here links to code where we fetch IPAddressClaims and IPAddresses
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/controllers/openstackserver_controller.go#L575
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/controllers/openstackserver_controller.go#L624

However, maybe the watch and RBAC are not needed anymore in the OpenstackMachine controller.

Comment (EmilienM) [reply controllers/openstackserver_controller.go:81]: Indeed I'm not sure either and we have no CI coverage for that feature :confused: ...

**Comment by mdbooth** [comment]
/assign

I'm going to try to dig in to this. First thoughts (haven't looked at the code in detail, yet):

All of these controllers run in the same manager, therefore they all have the same RBAC. So while it's good practice for each controller to declare the RBAC it requires, if it's in the same manager as some other controller which already has all the required permissions it shouldn't actually be necessary. Therefore, whether it's the machine controller or the server controller shouldn't make any difference here.

We're also running in the same manager as the IPAM controller itself. Is the real problem that the declarations are missing from the IPAM controller?

Some nits:
* if we're declaring the RBAC requirements of the server controller specifically, it should not need write privileges to any status subresource except its own.
* I'm guessing the machine controller doesn't need to declare this requirement at all, because it delegates it to the server controller?
* Either way, it should make no difference to the emitted RBAC because the IPAM controller should presumably already have it

I agree it sounds like we could do with an e2e test, but I wouldn't hold up fixing a critical bug for that.

**Comment by MisterKind** [comment]
Hello, is there something I can do to help you ?

**Comment by MisterKind** [comment]
Is there anything I can do to help this PR move forward ?

**Review by lentzi90 — COMMENTED** [review]
Sorry for the delay.
I say we take this in. The RBAC doesn't change so the kubebuilder directives could be removed, but they don't hurt either.
/lgtm
/cc @mdbooth @EmilienM

**Comment by MisterKind** [comment]
Hello,
How can I help move this PR please ?
\cc @mdbooth  @EmilienM
