### PR TITLE
Fix cluster nil lead to panic

### LINKED ISSUE #317: check nil cluster is provided
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
At the moment, cluster-api-provider-openstack panics with a nil pointer if there is no cluster
We might want to make sure to return an error if a nil cluster is provided.

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by jichenjc**
cluster variable might be be nil due to some configuration error
so this patch adds a check of cluster status before use it

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #317 

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

File: pkg/cloud/openstack/cluster/actuator.go [hunk 1]
```diff
@@ -42,6 +42,10 @@ func NewActuator(params providerv1openstack.ActuatorParams) (*Actuator, error) {
 // Reconcile creates or applies updates to the cluster.
 func (a *Actuator) Reconcile(cluster *clusterv1.Cluster) error {
 	klog.Infof("Reconciling cluster %v.", cluster.Name)
+	if cluster == nil {
```
Comment (gyliu513) [inline pkg/cloud/openstack/cluster/actuator.go]: This checking should right before the log at Line44?

Comment (jichenjc) [reply pkg/cloud/openstack/cluster/actuator.go]: right, I didn't pay attention, thanks for pointing out
