### PR TITLE
🐛 Fix auto generate security groups

### LINKED ISSUE #553: Can not access applications via LoadBalancer
/kind bug

**What steps did you take and what happened:**
I deployed a web application using LoadBalancer type service on kubernetes cluster deployed by cluster-api-provider-openstack with Octavia. The application can not be accessed via loadbalancer.

**What did you expect to happen:**

The application can be accessed via loadbalancer.

**Anything else you would like to add:**
The application could be acccessed by adding security group rule which accept NodePort services(port range 30000-32767) to worker nodes.
I think we should update security group rules according to [Check required ports](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#check-required-ports)

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by hidekazuna**
**What this PR does / why we need it**:

This PR updates generate security groups to follow kubeadm install documentation.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #553 

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
Fixed generate security groups to follow kubeadm install documentation for using NodePort services.

```

### CODE REVIEW

File: pkg/cloud/services/networking/securitygroups.go [hunk 1]
```diff
@@ -147,21 +153,35 @@ func generateControlPlaneGroup(clusterName string) infrav1.SecurityGroup {
 					RemoteIPPrefix: "0.0.0.0/0",
 				},
 				{
-					Direction:      "ingress",
-					EtherType:      "IPv4",
-					PortRangeMin:   22,
-					PortRangeMax:   22,
```
Comment (jichenjc) [inline pkg/cloud/services/networking/securitygroups.go:153]: maybe I missed something ,does this means not able to ssh anymore?

File: pkg/cloud/services/networking/securitygroups.go [hunk 2]
```diff
@@ -147,21 +153,35 @@ func generateControlPlaneGroup(clusterName string) infrav1.SecurityGroup {
...
 			},
 			defaultRules...,
 		),
 	}
 }
 
-func generateGlobalGroup(clusterName string) infrav1.SecurityGroup {
-	secGroupName := fmt.Sprintf("%s-cluster-%s-secgroup-%s", secGroupPrefix, clusterName, globalSuffix)
+func (s *Service) generateWorkerGroup(clusterName string) infrav1.SecurityGroup {
+	secGroupName := fmt.Sprintf("%s-cluster-%s-secgroup-%s", secGroupPrefix, clusterName, workerSuffix)
```
Comment (jichenjc) [inline pkg/cloud/services/networking/securitygroups.go:178]: nit: better us secWorkerGroupName as variable``

File: pkg/cloud/services/networking/securitygroups.go [hunk 3]
```diff
@@ -147,21 +153,35 @@ func generateControlPlaneGroup(clusterName string) infrav1.SecurityGroup {
...
+	secControlPlaneGroupName := fmt.Sprintf("%s-cluster-%s-secgroup-%s", secGroupPrefix, clusterName, controlPlaneSuffix)
+
+	secControlPlaneGroup, err := s.getSecurityGroupByName(secControlPlaneGroupName)
+	if err != nil || secControlPlaneGroup == nil || secControlPlaneGroup.ID == "" {
+		return infrav1.SecurityGroup{}
```
Comment (jichenjc) [inline pkg/cloud/services/networking/securitygroups.go:183]: so we have to have control plane secure group in order to create network ?
is there some edge case e.g controller doesn't use it while worker use it?
I knew it's rare so just ask in case we know it

File: pkg/cloud/services/networking/securitygroups.go (hunk 1 above)
Comment (hidekazuna) [reply pkg/cloud/services/networking/securitygroups.go:153]: We can not use ssh access anymore. Because I really implemented [Check required ports](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#check-required-ports).

File: pkg/cloud/services/networking/securitygroups.go (hunk 2 above)
Comment (hidekazuna) [reply pkg/cloud/services/networking/securitygroups.go:178]: OK, I will fix.

File: pkg/cloud/services/networking/securitygroups.go (hunk 1 above)
Comment (jichenjc) [reply pkg/cloud/services/networking/securitygroups.go:153]: I am ok with it ,however, for debug, without ssh it will be really not easy
we at least need provide a way to enable ssh

or at worst case, create a doc guide user how to enable it by modifying the code...

File: pkg/cloud/services/networking/securitygroups.go (hunk 3 above)
Comment (hidekazuna) [reply pkg/cloud/services/networking/securitygroups.go:183]: If ManagedSecurityGroups is true, control plane security group and worker security group will be created by following  [Check required ports](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#check-required-ports). If we do not like these rules, set ManagedSecurityGroups to false and specify existing security groups.

File: pkg/cloud/services/networking/securitygroups.go (hunk 1 above)
Comment (hidekazuna) [reply pkg/cloud/services/networking/securitygroups.go:153]: We can open ssh port by changing security groups dynamically after VM has been booted if some problems occurred( Actually I was doing so 😅 ).
I totally agree adding documentation.

Comment (hidekazuna) [reply pkg/cloud/services/networking/securitygroups.go:153]: It is much easier to add existing security group to your yaml than modifying the code like the following.

```yaml
      securityGroups:
      - name: k8s-cluster-default-capi-quickstart-secgroup-controlplane
      - name: default
```
this default security group enables ssh port.

Comment (hidekazuna) [reply pkg/cloud/services/networking/securitygroups.go:153]: @jichenjc Updated docs.
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/555/files#diff-76e731333fb756df3bff5ddb3b731c46

File: pkg/cloud/services/networking/securitygroups.go (hunk 2 above)
Comment (hidekazuna) [reply pkg/cloud/services/networking/securitygroups.go]: fixed.

File: pkg/cloud/services/networking/securitygroups.go (hunk 1 above)
Comment (jichenjc) [reply pkg/cloud/services/networking/securitygroups.go:153]: thanks for the update

File: pkg/cloud/services/networking/securitygroups.go (hunk 3 above)
Comment (jichenjc) [reply pkg/cloud/services/networking/securitygroups.go:183]: thanks, the info works for me

**Comment by prankul88** [comment]
@hidekazuna Thanks for the PR! Will take a look at it later today.

File: pkg/cloud/services/networking/securitygroups.go [hunk 4]
```diff
@@ -56,14 +56,26 @@ func (s *Service) ReconcileSecurityGroups(clusterName string, openStackCluster *
 		s.logger.V(4).Info("No need to reconcile security groups", "cluster", clusterName)
 		return nil
 	}
+
+	secControlPlaneGroupName := fmt.Sprintf("%s-cluster-%s-secgroup-%s", secGroupPrefix, clusterName, controlPlaneSuffix)
+	var err error
+	err = s.createSecurityGroupIfNotExists(secControlPlaneGroupName)
+	if err != nil {
```
Comment (sbueringer) [inline pkg/cloud/services/networking/securitygroups.go:63]:
```suggestion
	if err := s.createSecurityGroupIfNotExists(secControlPlaneGroupName); err != nil {
```

File: pkg/cloud/services/networking/securitygroups.go [hunk 5]
```diff
@@ -56,14 +56,26 @@ func (s *Service) ReconcileSecurityGroups(clusterName string, openStackCluster *
...
+		return nil
+	}
+	secWorkerGroupName := fmt.Sprintf("%s-cluster-%s-secgroup-%s", secGroupPrefix, clusterName, workerSuffix)
+	err = s.createSecurityGroupIfNotExists(secWorkerGroupName)
+	if err != nil {
```
Comment (sbueringer) [inline pkg/cloud/services/networking/securitygroups.go:68]: same here

File: pkg/cloud/services/networking/securitygroups.go [hunk 6]
```diff
@@ -147,51 +153,57 @@ func generateControlPlaneGroup(clusterName string) infrav1.SecurityGroup {
...
 			defaultRules...,
 		),
 	}
 }
 
-func generateGlobalGroup(clusterName string) infrav1.SecurityGroup {
-	secGroupName := fmt.Sprintf("%s-cluster-%s-secgroup-%s", secGroupPrefix, clusterName, globalSuffix)
+func (s *Service) generateWorkerGroup(clusterName string) infrav1.SecurityGroup {
+	secWorkerGroupName := fmt.Sprintf("%s-cluster-%s-secgroup-%s", secGroupPrefix, clusterName, workerSuffix)
+	secControlPlaneGroupName := fmt.Sprintf("%s-cluster-%s-secgroup-%s", secGroupPrefix, clusterName, controlPlaneSuffix)
```
Comment (sbueringer) [inline pkg/cloud/services/networking/securitygroups.go:179]: what is the dependency from the workersecgroup to the control plane sec group?

File: pkg/cloud/services/networking/securitygroups.go [hunk 7]
```diff
@@ -147,51 +153,57 @@ func generateControlPlaneGroup(clusterName string) infrav1.SecurityGroup {
...
+	}
 
 	// As above, hardcoded rules.
 
 	return infrav1.SecurityGroup{
-		Name: secGroupName,
+		Name: secWorkerGroupName,
 		Rules: append(
 			[]infrav1.SecurityGroupRule{
 				{
```
Comment (sbueringer) [inline pkg/cloud/services/networking/securitygroups.go:192]: Looks to me like the workers cannot communicate with each other anymore? If I'm right, isn't that a problem? 
Also how does the communication between control plane and workers and back works now?

File: pkg/cloud/services/networking/securitygroups.go (hunk 4 above)
Comment (hidekazuna) [reply pkg/cloud/services/networking/securitygroups.go:63]: Thanks, will fix.

File: pkg/cloud/services/networking/securitygroups.go (hunk 6 above)
Comment (hidekazuna) [reply pkg/cloud/services/networking/securitygroups.go:179]: The worker security group accept 10250/tcp from control plane security group. Please see line 206.

File: pkg/cloud/services/networking/securitygroups.go (hunk 7 above)
Comment (hidekazuna) [reply pkg/cloud/services/networking/securitygroups.go:192]: I understand I am missing considering the cni plugin. Let's add the rule to allow workers to communicate each other.
In terms of the communication between controller and worker, controller accept 6443/tcp(kube-apiserver) from all including worker nodes, and worker accepts 10250/tcp(kubelet API) from controller. This should work fine.

File: pkg/cloud/services/networking/securitygroups.go (hunk 5 above)
Comment (hidekazuna) [reply pkg/cloud/services/networking/securitygroups.go:68]: will fix.

File: pkg/cloud/services/networking/securitygroups.go (hunk 7 above)
Comment (jichenjc) [reply pkg/cloud/services/networking/securitygroups.go:192]: we might have more workers after the init cluster deploy, will this also considered?
maybe need some detail thought on what we expect the cluster network to be provisioned by default and guide user to add advanced by their own..

Comment (sbueringer) [reply pkg/cloud/services/networking/securitygroups.go:192]: @hidekazuna worker<=> master sounds good. So you also add a rule that the worker nodes can communicate with each other, right?

File: pkg/cloud/services/networking/securitygroups.go (hunk 6 above)
Comment (sbueringer) [reply pkg/cloud/services/networking/securitygroups.go:179]: Seems a bit implicit to just return an empty security group if the control plane group doesn't exist. I don't get the logic behind that. What do we want to achieve with that?

File: pkg/cloud/services/networking/securitygroups.go [hunk 8]
```diff
@@ -56,14 +56,26 @@ func (s *Service) ReconcileSecurityGroups(clusterName string, openStackCluster *
...
 	desiredSecGroups := map[string]infrav1.SecurityGroup{
-		"controlplane": generateControlPlaneGroup(clusterName),
-		"global":       generateGlobalGroup(clusterName),
+		"controlplane": s.generateControlPlaneGroup(clusterName),
+		"worker":       s.generateWorkerGroup(clusterName),
 	}
 	observedSecGroups := make(map[string]*infrav1.SecurityGroup)
 
 	for k, desiredSecGroup := range desiredSecGroups {
-		s.logger.Info("Reconciling security group", "name", desiredSecGroup.Name)
```
Comment (prankul88) [inline pkg/cloud/services/networking/securitygroups.go:66]: @hidekazuna Just curious. Won't it be better to keep this? Just to log which security group is being reconciled.

File: pkg/cloud/services/networking/securitygroups.go [hunk 9]
```diff
@@ -229,7 +241,7 @@ func matchGroups(desired, observed infrav1.SecurityGroup) bool {
 
 // reconcileGroup reconciles an already existing observed group by essentially emptying out all the rules and
```
Comment (prankul88) [inline pkg/cloud/services/networking/securitygroups.go:242]: Nit: Instead of reconcileGroup it must be `reconcileGroupRules`

File: pkg/cloud/services/networking/securitygroups.go (hunk 7 above)
Comment (hidekazuna) [reply pkg/cloud/services/networking/securitygroups.go:192]: @sbueringer Yes, I will also add the rule you mentioned.

File: pkg/cloud/services/networking/securitygroups.go (hunk 6 above)
Comment (hidekazuna) [reply pkg/cloud/services/networking/securitygroups.go:179]: I will fix to return error if the control plane security group does not exist.

File: pkg/cloud/services/networking/securitygroups.go (hunk 4 above)
Comment (hidekazuna) [reply pkg/cloud/services/networking/securitygroups.go]: fixed

File: pkg/cloud/services/networking/securitygroups.go (hunk 5 above)
Comment (hidekazuna) [reply pkg/cloud/services/networking/securitygroups.go]: fixed.

File: pkg/cloud/services/networking/securitygroups.go (hunk 9 above)
Comment (hidekazuna) [reply pkg/cloud/services/networking/securitygroups.go]: @prankul88 fixed.

File: pkg/cloud/services/networking/securitygroups.go (hunk 7 above)
Comment (hidekazuna) [reply pkg/cloud/services/networking/securitygroups.go:196]: @sbueringer Ther rule was added here:
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/555/files#diff-981e50f3b13da070546823dd24e18b32R197-R211

File: pkg/cloud/services/networking/securitygroups.go (hunk 6 above)
Comment (hidekazuna) [reply pkg/cloud/services/networking/securitygroups.go:180]: @sbueringer I fixed this as below:
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/555/files#diff-981e50f3b13da070546823dd24e18b32R182-R188

File: pkg/cloud/services/networking/securitygroups.go (hunk 8 above)
Comment (prankul88) [reply pkg/cloud/services/networking/securitygroups.go:66]: @hidekazuna Got it. Thanks

**Comment by prankul88** [comment]
LGTM

**Comment by hidekazuna** [comment]
@jichenjc @sbueringer Could you review again?

File: pkg/cloud/services/networking/securitygroups.go (hunk 7 above)
Comment (hidekazuna) [reply pkg/cloud/services/networking/securitygroups.go:196]: @sbueringer @jichenjc I studied calico and skeptical about adding the rule for worker communication now. Calico default networking requirement is bidirectional tcp 179 and IPinIP. I created new security group including the rule allowing bidirectional tcp 179 and IPinIP, and added the group to both controllers and workers. It is working fine.
We should leave the issue due to depending on the CNI implementation.

Comment (jichenjc) [reply pkg/cloud/services/networking/securitygroups.go:196]: I am not fully understand the comments above
>>>I created new security group including the rule allowing bidirectional tcp 179 and IPinIP, and added the group to both controllers and workers. 

you mean after your change, the cluster still not work and you have to create the rules manually? as we are provide solution to `create a k8s cluster` so we should consider how to enhance it , if it's a generic requirements , we need talk to cluster-api folks?

Comment (hidekazuna) [reply pkg/cloud/services/networking/securitygroups.go:196]: All nodes are ready status, but pod to pod communication is not good. I think it is not good before my change. Kubespray doc says  [in OpenStack you must allow ipip traffic in your security groups ](https://github.com/kubernetes-sigs/kubespray/blob/master/docs/calico.md#cloud-providers-configuration).

Comment (hidekazuna) [reply pkg/cloud/services/networking/securitygroups.go:196]: Calico is just an example for Cluster API. So we should leave the issue for users.

Comment (hidekazuna) [reply pkg/cloud/services/networking/securitygroups.go:196]: @sbueringer @jichenjc I found [cluster-api-provider-aws implementation](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/pkg/cloud/services/ec2/securitygroups.go#L368-L488)! I will follow this implementaion 😃

Comment (jichenjc) [reply pkg/cloud/services/networking/securitygroups.go:196]: seems that's for calico only :)

Comment (hidekazuna) [reply pkg/cloud/services/networking/securitygroups.go:196]: now we understand cluster api is calico only :)

Comment (jichenjc) [reply pkg/cloud/services/networking/securitygroups.go:196]: https://github.com/kubernetes-sigs/cluster-api/issues/3174 opened

File: pkg/cloud/services/networking/securitygroups.go [hunk 10]
```diff
@@ -56,14 +56,27 @@ func (s *Service) ReconcileSecurityGroups(clusterName string, openStackCluster *
 		s.logger.V(4).Info("No need to reconcile security groups", "cluster", clusterName)
 		return nil
 	}
+
+	secControlPlaneGroupName := fmt.Sprintf("%s-cluster-%s-secgroup-%s", secGroupPrefix, clusterName, controlPlaneSuffix)
```
Comment (sbueringer) [inline pkg/cloud/services/networking/securitygroups.go:60]: this name is calculated here and in generateControlPlaneGroup and in generateWorkerGroup similar holds for the worker group name. Can we make sure we have only one place where we generate the sec group name and then hand it over?

File: pkg/cloud/services/networking/securitygroups.go (hunk 6 above)
Comment (sbueringer) [reply pkg/cloud/services/networking/securitygroups.go:180]: Can we already return the securityGroup in line 61 (call to createSecurityGroupIfNotExists) and then just hand it over to generateWorkerGroup so we don't need the additional lookup?

File: pkg/cloud/services/networking/securitygroups.go (hunk 7 above)
Comment (sbueringer) [reply pkg/cloud/services/networking/securitygroups.go:196]: Okay so if calico works now, it's fine for me to resolve this conversation.

Comment (hidekazuna) [reply pkg/cloud/services/networking/securitygroups.go:196]: Calico is not working as of now. Pod to pod communication does not work. I will fix.

File: pkg/cloud/services/networking/securitygroups.go (hunk 6 above)
Comment (hidekazuna) [reply pkg/cloud/services/networking/securitygroups.go]: I made generateControlPlaneSecuriyGroup and generateWorkerGroup into generateDesiredSecGroups, and build security group names only once.

File: pkg/cloud/services/networking/securitygroups.go (hunk 10 above)
Comment (hidekazuna) [reply pkg/cloud/services/networking/securitygroups.go:60]: Generating the sec group names is now only once at the beginning of ReconcileSecurityGroups.

**Comment by sbueringer** [comment]
/approve

@hidekazuna  I assume it's tested in your environment and it works, I'm not using the feature :)
