### PR TITLE
do not set failure reason/message when LB not created

### LINKED ISSUE #1574: Cluster stays on phase:  `failed` after Octavia downtime
/kind bug
Hello

**What steps did you take and what happened:**
We had a downtime on our octavia api. During that time CAPO could not reconcile the loadbalancers:
```
E0601 07:24:27.848387       1 controller.go:326] "Reconciler error" err="failed to reconcile load balancer: load balancer \"k8s-clusterapi-cluster-daphne-satellite-dev-kubeapi\" with id 121470d9-6867-45c3-84e4-fc31c4ce860a is not active after timeout: Gateway Timeout" controller="openstackcluster" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="OpenStackCluster" OpenStackCluster="daphne/satellite-dev-q5jjz" namespace="daphne" name="satellite-dev-q5jjz" reconcileID=b9d32e02-4f64-4174-aeac-f46e69f9de64
E0601 07:24:28.598708       1 controller.go:326] "Reconciler error" err="reconcile load balancer member: network.APIServerLoadBalancer is not yet available in openStackCluster.Status" controller="openstackmachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="OpenStackMachine" OpenStackMachine="daphne/satellite-dev-control-plane-fcbs5-rj2kp" namespace="daphne" name="satellite-dev-control-plane-fcbs5-rj2kp" reconcileID=b87acea3-6b50-4bab-9203-1af22c6cfc3d
E0601 07:24:28.601363       1 controller.go:326] "Reconciler error" err="reconcile load balancer member: network.APIServerLoadBalancer is not yet available in openStackCluster.Status" controller="openstackmachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="OpenStackMachine" OpenStackMachine="daphne/satellite-dev-control-plane-fcbs5-sxprk" namespace="daphne" name="satellite-dev-control-plane-fcbs5-sxprk" reconcileID=5f80fd1f-647f-4574-a237-e358f43b714d
E0601 07:24:28.728599       1 controller.go:326] "Reconciler error" err="reconcile load balancer member: network.APIServerLoadBalancer is not yet available in openStackCluster.Status" controller="openstackmachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="OpenStackMachine" OpenStackMachine="daphne/satellite-dev-control-plane-fcbs5-6r669" namespace="daphne" name="satellite-dev-control-plane-fcbs5-6r669" reconcileID=be32e507-a4c1-434c-9170-2278bdc3c7f1
```

Moreover, this was added to the `Cluster` resource:
```
  Failure Message:       Failure detected from referenced resource infrastructure.cluster.x-k8s.io/v1alpha6, Kind=OpenStackCluster with name "satellite-dev-q5jjz": failed to reconcile load balancer: load balancer "k8s-clusterapi-cluster-daphne-satellite-dev-kubeapi" with id 121470d9-6867-45c3-84e4-fc31c4ce860a is not active after timeout: Gateway Timeout
  Failure Reason:        UpdateError
```

After a while octavia service was fixed and was operational. Capo was able to reconcile the loadbalancer (nothing had changed) and no more errors were on the logs. The cluster is fully operational (also was during octavia downtime).

But the cluster is stuch on phase: `Failed` with the same Failure message and reason as above.

**What did you expect to happen:**
The cluster should not stay in the `failed` state.

**Anything else you would like to add:**
From a short chat on capi slack channel:
> Failures in CAPI object statuses represent terminal failures - so if there's a terminal failure on an infrastructure object like a load balancer CAPI treats this as a state that can not be recovered from. Transient issues should not result in Failures in status.

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): 0.7.1
- Cluster-API version: 1.4.2
- OpenStack version: Victoria
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by jichenjc**
**What this PR does / why we need it**:

Do not set failureReason & failureMessage of the OpenStackCluster when reconcile LB not successful 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1574 

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**TODOs**:

- [ ] squashed commits
- if necessary:
  - [ ] includes documentation
  - [ ] adds unit tests

/hold

### CODE REVIEW

File: pkg/cloud/services/loadbalancer/loadbalancer.go [hunk 1]
```diff
@@ -156,7 +156,7 @@ func (s *Service) ReconcileLoadBalancer(openStackCluster *infrav1.OpenStackClust
 		AllowedCIDRs: allowedCIDRs,
 		Tags:         lb.Tags,
 	}
-	return nil
+	return true, nil
```
Comment (lentzi90) [inline pkg/cloud/services/loadbalancer/loadbalancer.go:159]: Why return `true` here? It seems conflicting to me: no error but terminal error :thinking:

File: pkg/cloud/services/loadbalancer/loadbalancer.go [hunk 2]
```diff
@@ -60,7 +60,7 @@ func (s *Service) ReconcileLoadBalancer(openStackCluster *infrav1.OpenStackClust
 
 	providers, err := s.loadbalancerClient.ListLoadBalancerProviders()
 	if err != nil {
-		return err
+		return true, err
```
Comment (lentzi90) [inline pkg/cloud/services/loadbalancer/loadbalancer.go:63]: I'm not sure if this should be a terminal error. What if there was some temporary network issue?

**Review by lentzi90 — COMMENTED** [review]
I'm not sure about this. Basically I wonder if we ever really have terminal errors. Perhaps some kind of misconfiguration? 
The alternative that I am thinking about is that we could emit events instead of setting `failureMessage` and `failureReason` [here](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/5ac49e7475de3c9b95df3d73208b79319fc322bc/controllers/openstackcluster_controller.go#L622-L623). The description of these fields mentions this as an alternative:

> Any transient errors that occur during the reconciliation of
> OpenStackClusters can be added as events to the OpenStackCluster object
> and/or logged in the controller's output.

File: pkg/cloud/services/loadbalancer/loadbalancer.go (hunk 2 above)
Comment (jichenjc) [reply pkg/cloud/services/loadbalancer/loadbalancer.go:63]: right ,I think should make it false

File: pkg/cloud/services/loadbalancer/loadbalancer.go (hunk 1 above)
Comment (jichenjc) [reply pkg/cloud/services/loadbalancer/loadbalancer.go:159]: ok, make it false :)
technically we return err=nil so true/false doesn't matter :)

**Comment by jichenjc** [comment]
>>>The alternative that I am thinking about is that we could emit events instead of setting failureMessage and failureReason [here](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/5ac49e7475de3c9b95df3d73208b79319fc322bc/controllers/openstackcluster_controller.go#L622-L623). The description of these fields mentions this as an alternative:

I think general rule is if it's misconfiguration ,we should set error message/reason ..
if it's temporary error like can't talk to openstack, should not set it 

emit events is also good idea , I think we used it a lot already

**Review by lentzi90 — COMMENTED** [review]
/lgtm
As mentioned before, I think we may want to restructure this a bit more later, but for now I think it will do and should solve the issue :slightly_smiling_face:

**Comment by jichenjc** [comment]
/hold cancel

let's merge this and if there's another request come out, let's continue to improve
