### PR TITLE
🐛 port: don't add any SGs when port security is disabled

### LINKED ISSUE #2158: Impossible to disable portSecurity on a port in OpenStackMachine
/kind bug

**What steps did you take and what happened:**

if `managedSecurityGroups` is enabled, each port that is created will get the security group that belongs to it (master or worker).
But if we explicitly set `disablePortSecurity: true` on that port, it'll still try to get the CAPO-managed security group and therefore Neutron will fail to create that port. A port with no security can't have security groups in its spec.

**What did you expect to happen:**

We shouldn't create a port that has explicit disablePortSecurity with security groups.

### PR DESCRIPTION
**Pull request by EmilienM**
**What this PR does / why we need it**:

When port security is disabled on a port, don't add any security group
to the port options.

Skip the security groups when resolving the ports spec.
Report an error when a port tries to be created with both security
groups and disable port security to true.
Adds unit tests coverage for these scenarios.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2158

### CODE REVIEW

File: pkg/cloud/services/networking/port.go [hunk 1]
```diff
@@ -170,6 +170,9 @@ func (s *Service) CreatePort(eventObject runtime.Object, portSpec *infrav1.Resol
 		createOpts.FixedIPs = fixedIPs
 	}
 	if portSpec.SecurityGroups != nil {
+		if ptr.Deref(portSpec.DisablePortSecurity, false) {
+			return nil, errors.New("security groups cannot be set when port security is disabled")
+		}
```
Comment (mdbooth) [inline pkg/cloud/services/networking/port.go:175]: IIRC if you try to add a security group to a port with port security disabled you get an error, right? i.e. It's not just that it ignores the option, but it actually won't add the security groups?

If so, we should be able to safely add API validation for this instead, because we know there is no working configuration with it set.

i.e. We should write this as CEL instead. The tests would be in apivalidations.

**Review by mdbooth — COMMENTED** [review]
Change looks sound. If my assumption about the error is correct, we should add API validation instead of runtime validation, though.

File: pkg/cloud/services/networking/port.go (hunk 1 above)
Comment (EmilienM) [reply pkg/cloud/services/networking/port.go:175]: > IIRC if you try to add a security group to a port with port security disabled you get an error, right? i.e. It's not just that it ignores the option, but it actually won't add the security groups?

yeah right. And good points on API validations. I'll check that.

Comment (EmilienM) [reply pkg/cloud/services/networking/port.go:175]: I've added tests in the webhook like other fields and tests in API validations. I've let this check on purpose because:
1. it doesn't hurt, I think
2. it's safe and it makes sense to report an error and not let it through anyway.

File: pkg/webhooks/openstackserver_webhook.go [hunk 2]
```diff
@@ -64,6 +65,12 @@ func (*openStackServerWebhook) ValidateCreate(_ context.Context, objRaw runtime.
 		}
 	}
 
+	for _, port := range newObj.Spec.Ports {
+		if ptr.Deref(port.DisablePortSecurity, false) && len(port.SecurityGroups) > 0 {
+			allErrs = append(allErrs, field.Forbidden(field.NewPath("spec", "ports"), "cannot have security groups when DisablePortSecurity is set to true"))
+		}
+	}
```
Comment (mdbooth) [inline pkg/webhooks/openstackserver_webhook.go:72]: Is there any reason we can't do this in CEL? We haven't added any new logic to the webhooks in a while and I'd like to phase them out.

File: pkg/cloud/services/networking/port.go (hunk 1 above)
Comment (mdbooth) [reply pkg/cloud/services/networking/port.go:175]: Ack to leaving the check in.

I'd prefer we didn't add anything new to the webhooks, though, unless we absolutely have to. I take a look to see how easy the CEL is to write.

Comment (EmilienM) [reply pkg/cloud/services/networking/port.go:175]: that was my thought when I looked at CEL and why I took the webhook way instead :confused:

**Comment by EmilienM** [comment]
if you can /approve instead so I can ask @MaysaMacedo to take a look as well. Thanks

**Comment by EmilienM** [comment]
@MaysaMacedo it merged by accident but when time permits, please have a look and let me know if anything is wrong, we'll fix afterwards. Thanks
