### PR TITLE
:bug: if the openstackcluster was ready, we don't want to set a terminalError

### LINKED ISSUE #2097: Cluster stays in Failed state after Credentials rotations
/kind bug

The Cluster object stays in failed state after a credentials problem is resolved.

      failureMessage: |
          Failure detected from referenced resource infrastructure.cluster.x-k8s.io/v1beta1, Kind=OpenStackCluster with name "rotate-creds-cnrwq": failed to reconcile external network: failed to get external network: Unable to re-authenticate: Expected HTTP response code [200] when accessing [GET https://url/v2.0/networks/54258498-a513-47da-9369-1a644e4be692], but got 401 instead
          {"error": {"code": 401, "title": "Unauthorized", "message": "The request you have made requires authentication."}}: Resource not found: [POST https://url/v3/auth/tokens], error message: {"error":{"code":404,"message":"Could not find Application Credential: OLD ID.","title":"Not Found"}}

**What steps did you take and what happened:**

Delete used appcreds and wait for failure to accour
Create new app creds and update all resources
Verify that all actions are possible again, on mgmt cluster or in cluster

**What did you expect to happen:**
Cluster state is good again after fix

**Anything else you would like to add:**
Looks like Creds errors are handelt as a terminal error and not as a transient error. 
Seems to be like a problem we had with the Machines too

Code for the machine problem as an idea how to fix: [https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/7a19fb6f038[…]a31df228877a446b9b99/controllers/openstackmachine_controller.go](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/7a19fb6f038ece8702dea31df228877a446b9b99/controllers/openstackmachine_controller.go#L651-L660)

Code in Openstack cluster controller with the problem: [https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/7a19fb6f038[…]a31df228877a446b9b99/controllers/openstackcluster_controller.go](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/7a19fb6f038ece8702dea31df228877a446b9b99/controllers/openstackcluster_controller.go#L914-L918)

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): v010.3
- Cluster-API version: v1.7.3

### PR DESCRIPTION
**Pull request by qeqar**
f.e if the creds break, but the cluster was ready, the operator can fix it.

**What this PR does / why we need it**:
Use transient Error if the Openstackcluster was once ready.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2097

**Special notes for your reviewer**:

/hold

### CODE REVIEW

**Comment by EmilienM** [comment]
What seems wrong to me, is that if a user changes the bastion spec with a new flavor, that new flavor doesn't exist in Nova, the controller fails to create the bastion and wants to update `FailureReason`, it won't because cluster was `Ready`.
I'm wondering if we should rather set Readiness to false into this function as well?

**Comment by qeqar** [comment]
As this is fixable by fixing the flavor name in the CR, it seems to be the same type of error. So it should not be permanently too.

Setting ready to false is done in no case at the moment, so this would change the behavior, if that is ok, i can put it in the else path, but then i need so find the proper place(s) to set it true again.

**Comment by EmilienM** [comment]
I'll ask @lentzi90 and @mdbooth what they think.

**Comment by qeqar** [comment]
After some additional thinking, would setting ready to false, removes the validly of my if clause.

So first: it need to be set on every error, as a permanent error is more critical an should result in an ready false and second if we have two problems, f.e. some error and we activate the bastion host to have look and then do a flavor typo, it will go directly to a permanent error, as ready was already false.

If we start setting ready to false after it was set to true, we need to find a different switch between permanent and transient errors.

**Comment by mdbooth** [comment]
I've asked about setting `Ready` to `false` here: https://kubernetes.slack.com/archives/C8TSNPY4T/p1716892079243969

File: controllers/openstackcluster_controller.go [hunk 1]
```diff
@@ -912,9 +912,11 @@ func (r *OpenStackClusterReconciler) SetupWithManager(ctx context.Context, mgr c
 }
 
 func handleUpdateOSCError(openstackCluster *infrav1.OpenStackCluster, message error) {
-	err := capierrors.UpdateClusterError
-	openstackCluster.Status.FailureReason = &err
-	openstackCluster.Status.FailureMessage = ptr.To(message.Error())
+	if !openstackCluster.Status.Ready {
```
Comment (mdbooth) [inline controllers/openstackcluster_controller.go:915]: I'd prefer to not call this method for a transient error in the first place. This would prevent anything from being fatal after the cluster is ready, which probably isn't right either.

Comment (qeqar) [reply controllers/openstackcluster_controller.go]: Ok moved the ready check outside of the function. 

But there a 4 place i am not sure what to do:

fist case:  
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/controllers/openstackcluster_controller.go#L815-L822
Here some one added a terminal error to the function, but inside the function it never returns with terminalError true

the second case: 
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/controllers/openstackcluster_controller.go#L815-L822
In this function someone selected exactly one error already, but did not check against ready. 

In both cases i am not sure if we need to add the ready state check on top?

File: controllers/openstackcluster_controller.go [hunk 2]
```diff
@@ -731,7 +769,9 @@ func reconcilePreExistingNetworkComponents(scope *scope.WithLogger, networkingSe
 	if openStackCluster.Spec.Network != nil {
 		network, err := networkingService.GetNetworkByParam(openStackCluster.Spec.Network)
 		if err != nil {
-			handleUpdateOSCError(openStackCluster, fmt.Errorf("failed to find network: %w", err))
+			if !openStackCluster.Status.Ready {
+				handleUpdateOSCError(openStackCluster, fmt.Errorf("failed to find network: %w", err))
+			}
```
Comment (mdbooth) [inline controllers/openstackcluster_controller.go:774]: Ditto

File: controllers/openstackcluster_controller.go [hunk 3]
```diff
@@ -775,17 +815,24 @@ func reconcilePreExistingNetworkComponents(scope *scope.WithLogger, networkingSe
 func reconcileProvisionedNetworkComponents(networkingService *networking.Service, openStackCluster *infrav1.OpenStackCluster, clusterResourceName string) error {
 	err := networkingService.ReconcileNetwork(openStackCluster, clusterResourceName)
 	if err != nil {
-		handleUpdateOSCError(openStackCluster, fmt.Errorf("failed to reconcile network: %w", err))
+		if !openStackCluster.Status.Ready {
+			handleUpdateOSCError(openStackCluster, fmt.Errorf("failed to reconcile network: %w", err))
+		}
```
Comment (mdbooth) [inline controllers/openstackcluster_controller.go:820]: Ditto

File: controllers/openstackcluster_controller.go [hunk 4]
```diff
@@ -775,17 +815,24 @@ func reconcilePreExistingNetworkComponents(scope *scope.WithLogger, networkingSe
...
 		return fmt.Errorf("failed to reconcile network: %w", err)
 	}
 	err = networkingService.ReconcileSubnet(openStackCluster, clusterResourceName)
 	if err != nil {
-		handleUpdateOSCError(openStackCluster, fmt.Errorf("failed to reconcile subnets: %w", err))
+
+		if !openStackCluster.Status.Ready {
+			handleUpdateOSCError(openStackCluster, fmt.Errorf("failed to reconcile subnets: %w", err))
+		}
```
Comment (mdbooth) [inline controllers/openstackcluster_controller.go:828]: Ditto

File: controllers/openstackcluster_controller.go [hunk 5]
```diff
@@ -775,17 +815,24 @@ func reconcilePreExistingNetworkComponents(scope *scope.WithLogger, networkingSe
...
 		return fmt.Errorf("failed to reconcile subnets: %w", err)
 	}
 	err = networkingService.ReconcileRouter(openStackCluster, clusterResourceName)
 	if err != nil {
-		handleUpdateOSCError(openStackCluster, fmt.Errorf("failed to reconcile router: %w", err))
+		if !openStackCluster.Status.Ready {
+			handleUpdateOSCError(openStackCluster, fmt.Errorf("failed to reconcile router: %w", err))
+		}
```
Comment (mdbooth) [inline controllers/openstackcluster_controller.go:835]: Ditto

File: controllers/openstackcluster_controller.go [hunk 6]
```diff
@@ -839,7 +886,9 @@ func reconcileControlPlaneEndpoint(scope *scope.WithLogger, networkingService *n
 	case !ptr.Deref(openStackCluster.Spec.DisableAPIServerFloatingIP, false):
 		fp, err := networkingService.GetOrCreateFloatingIP(openStackCluster, openStackCluster, clusterResourceName, openStackCluster.Spec.APIServerFloatingIP)
 		if err != nil {
-			handleUpdateOSCError(openStackCluster, fmt.Errorf("floating IP cannot be got or created: %w", err))
+			if !openStackCluster.Status.Ready {
+				handleUpdateOSCError(openStackCluster, fmt.Errorf("floating IP cannot be got or created: %w", err))
+			}
```
Comment (mdbooth) [inline controllers/openstackcluster_controller.go:891]: Never terminal.

File: controllers/openstackcluster_controller.go [hunk 7]
```diff
@@ -854,7 +903,9 @@ func reconcileControlPlaneEndpoint(scope *scope.WithLogger, networkingService *n
 	// Control plane endpoint is not set, and none can be created
 	default:
 		err := fmt.Errorf("unable to determine control plane endpoint")
-		handleUpdateOSCError(openStackCluster, err)
+		if !openStackCluster.Status.Ready {
+			handleUpdateOSCError(openStackCluster, err)
+		}
```
Comment (mdbooth) [inline controllers/openstackcluster_controller.go:908]: Terminal if cluster is not ready.

File: controllers/openstackcluster_controller.go [hunk 8]
```diff
@@ -174,31 +174,41 @@ func (r *OpenStackClusterReconciler) reconcileDelete(ctx context.Context, scope
 		}
 
 		if err = loadBalancerService.DeleteLoadBalancer(openStackCluster, clusterResourceName); err != nil {
-			handleUpdateOSCError(openStackCluster, fmt.Errorf("failed to delete load balancer: %w", err))
+			if !openStackCluster.Status.Ready {
+				handleUpdateOSCError(openStackCluster, fmt.Errorf("failed to delete load balancer: %w", err))
+			}
```
[the remark this answers is not in the document]
Comment (EmilienM) [reply controllers/openstackcluster_controller.go:179]: Don't we want it stored in events though?

[the remark this answers is not in the document]
Comment (EmilienM) [reply controllers/openstackcluster_controller.go:179]: Ah nevermind this is not for events. This is the last error.
I agree this can't be the last error because other resources underneath can't be removed either if this one wasn't (hopefully my reasoning makes sense).

**Comment by qeqar** [comment]
Will have a look on Monday, if i have some time, then i am out for the rest of the week, so could take some time.

File: controllers/openstackcluster_controller.go (hunk 7 above)
Comment (qeqar) [reply controllers/openstackcluster_controller.go:908]: ok that is done

File: controllers/openstackcluster_controller.go [hunk 9]
```diff
@@ -503,7 +523,9 @@ func reconcileBastion(scope *scope.WithLogger, cluster *clusterv1.Cluster, openS
 	port, err := computeService.GetManagementPort(openStackCluster, instanceStatus)
 	if err != nil {
 		err = fmt.Errorf("getting management port for bastion: %w", err)
-		handleUpdateOSCError(openStackCluster, err)
+		if !openStackCluster.Status.Ready {
+			handleUpdateOSCError(openStackCluster, err)
+		}
```
[the remark this answers is not in the document]
Comment (qeqar) [reply controllers/openstackcluster_controller.go:528]: Not sure what to do here? The function is called in the cluster and the machine controller?

so should i rewrite it, that it is terminal in that sub case, or delete the complete check in the cluster controller?

**Review by lentzi90 — COMMENTED** [review]
Great!
/lgtm

We should probably think about adding conditions for some of the non-fatal errors at some point also

**Comment by qeqar** [comment]
Ok, i am not fully happy with setting the `isFatal` inside the function call, specially the true case. But should be ok for this one.

File: controllers/openstackcluster_controller.go [hunk 10]
```diff
@@ -643,7 +671,9 @@ func resolveLoadBalancerNetwork(openStackCluster *infrav1.OpenStackCluster, netw
 		if lbSpec.Network != nil {
 			lbNet, err := networkingService.GetNetworkByParam(lbSpec.Network)
 			if err != nil {
-				handleUpdateOSCError(openStackCluster, fmt.Errorf("failed to find loadbalancer network: %w", err))
+				if !openStackCluster.Status.Ready {
+					handleUpdateOSCError(openStackCluster, fmt.Errorf("failed to find loadbalancer network: %w", err))
+				}
```
[the remark this answers is not in the document]
Comment (qeqar) [reply controllers/openstackcluster_controller.go]: added both error cases as terminal

**Comment by qeqar** [comment]
Ok now re-based with main to get the #2109 error class changes and all occurrences updated

File: pkg/cloud/services/loadbalancer/loadbalancer.go [hunk 11]
```diff
@@ -82,6 +82,9 @@ func (s *Service) ReconcileLoadBalancer(openStackCluster *infrav1.OpenStackClust
 
 	lb, err := s.getOrCreateAPILoadBalancer(openStackCluster, clusterResourceName)
 	if err != nil {
+		if errors.Is(capoerrors.ErrFilterMatch, err) {
```
Comment (lentzi90) [inline pkg/cloud/services/loadbalancer/loadbalancer.go:85]: Should this be the other way around?
```suggestion
		if errors.Is(err, capoerrors.ErrFilterMatch) {
```

File: pkg/cloud/services/loadbalancer/loadbalancer.go [hunk 12]
```diff
@@ -107,6 +110,9 @@ func (s *Service) ReconcileLoadBalancer(openStackCluster *infrav1.OpenStackClust
 
 		fp, err := s.networkingService.GetOrCreateFloatingIP(openStackCluster, openStackCluster, clusterResourceName, floatingIPAddress)
 		if err != nil {
+			if errors.Is(capoerrors.ErrFilterMatch, err) {
```
Comment (lentzi90) [inline pkg/cloud/services/loadbalancer/loadbalancer.go:113]: Same here

**Review by lentzi90 — COMMENTED** [review]
Could you please squash the commits into one and check my question below

**Review by lentzi90 — COMMENTED** [review]
/approve

**Review by mdbooth — COMMENTED** [review]
/lgtm

Thank you!

**Comment by EmilienM** [comment]
Excellent contribution, thank you!
/hold cancel
