### PR TITLE
🐛 Prevent the bastion to be removed before it's been disabled

### LINKED ISSUE #1855: Changing Bastion instance spec doesn't work
/kind bug

**What steps did you take and what happened:**
* Deploy a cluster with a bastion
* Once the cluster is deployed, edit OpenStackCluster.Spec to disable the bastion like it's [documented](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/5cc483bfc6eae8a8b8a67b32e9b7af0bafa473ca/api/v1alpha8/openstackcluster_types.go#L157-L159). So later we can re-create it with another spec (e.g. new flavor).
* Removing `OpenStackCluster.Spec.Bastion` produces an error in CAPO:

```
I0202 02:37:59.557716      20 controller.go:115] "Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference" controller="openstackcluster" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="OpenStackCluster" OpenStackCluster="default/development-10884-rm62s" namespace="default" name="development-10884-rm62s" reconcileID="e0ebc724-7686-42ee-80fc-ce9984c1beb5"
```
(Here CAPO crashed in my lab, I had to restart it).

* Ok this time let's just switch `enabled` to False:
The bastion is removed and re-created immediately!
And `enabled` is True again (by itself).

**What did you expect to happen:**
The bastion should be deleted, so we can re-create it with a new spec.

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): current main
- Logs from when we delete the bastion to when it's re-created: https://hastebin.com/share/sabasopulu.python

### PR DESCRIPTION
**Pull request by EmilienM**
**What this PR does / why we need it**:

We now have a webhook that checks that a bastion has been disabled if a
change has to be made (update or delete) in the bastion field.
We also document it better.

Also, we added some code to prevent that we don't have a nil pointer if
the Spec.Bastion or Status.Bastion are unset.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1855

**TODOs**:

- [X] squashed commits
- if necessary:
  - [X] includes documentation
  - [X] adds unit tests

### CODE REVIEW

**Comment by EmilienM** [comment]
I manually tested it and it worked:

```
# openstackclusters.infrastructure.cluster.x-k8s.io "development-29561-rxprv" was not valid:
# * spec.bastion: Forbidden: cannot be removed before disabling it
```

File: api/v1alpha8/openstackcluster_webhook.go [hunk 1]
```diff
@@ -116,6 +116,13 @@ func (r *OpenStackCluster) ValidateUpdate(oldRaw runtime.Object) (admission.Warn
 		r.Spec.APIServerPort = 0
 	}
 
+	// Allow to remove the bastion spec only if it was disabled before.
+	if r.Spec.Bastion == nil {
+		if old.Spec.Bastion != nil && old.Spec.Bastion.Enabled {
```
Comment (EmilienM) [inline api/v1alpha8/openstackcluster_webhook.go:121]: note that I didn't add a guard to compare the old instance with the new one because there are complicated objects with filters. If we want to go down that path, let me know although I'm not sure it's desired.

Otherwise let me know if the doc content is enough.

File: docs/book/src/clusteropenstack/configuration.md [hunk 2]
```diff
@@ -654,6 +656,16 @@ spec:
...
 
+### Making changes to the bastion host
+
+Changes can be made to the bastion instance, like for example changing the flavor.
+First, you have to disable the bastion host by setting `enabled: false` in the `OpenStackCluster.Spec.Bastion` field. Then, you can make changes to the instance spec and re-enable the bastion host by setting `enabled: true` and by modifying the `OpenStackCluster.Spec.Bastion.Instance` field.
+
+### Disabling the bastion
+
+To disable the bastion host, set `enabled: false` in the `OpenStackCluster.Spec.Bastion` field. The bastion host will be deleted.
+Then you can remove the `OpenStackCluster.Spec.Bastion` field from the `OpenStackCluster` spec.
```
Comment (jichenjc) [inline docs/book/src/clusteropenstack/configuration.md:667]: line 667 seems confusing, what need to check or something to be done or how long should we wait?
that I can remove `OpenStackCluster.Spec.Bastion` field ? if it's disabled, why need remove them or what's the right timing to do so?

Comment (EmilienM) [reply docs/book/src/clusteropenstack/configuration.md:667]: I'll add more content.

File: controllers/openstackcluster_controller.go [hunk 3]
```diff
@@ -437,7 +443,15 @@ func reconcileBastion(scope scope.Scope, cluster *clusterv1.Cluster, openStackCl
 	return ctrl.Result{}, nil
 }
 
-func bastionToInstanceSpec(openStackCluster *infrav1.OpenStackCluster, clusterName string) *compute.InstanceSpec {
+func bastionToInstanceSpec(openStackCluster *infrav1.OpenStackCluster, clusterName string) (*compute.InstanceSpec, error) {
+	if openStackCluster.Spec.Bastion == nil {
```
Comment (EmilienM) [inline controllers/openstackcluster_controller.go:447]: @mdbooth the guard you asked for.

**Comment by huxcrux** [comment]
Looks good, the more detailed documentation looks to be easy to follow :+1: 

/lgtm

**Review by mdbooth — APPROVED** [review]
How do you fancy writing an e2e test for this? We keep breaking it.

**Comment by EmilienM** [comment]
> How do you fancy writing an e2e test for this? We keep breaking it.

On my list: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1822
My only problem is the limited amount of hours that we have per day.
