### PR TITLE
✨ Propagate OpenStackServer dependency errors to OpenStackMachine

### LINKED ISSUE #2265: Missing image is hard to debug
/kind bug

**What steps did you take and what happened:**

1. Create a cluster using an image that doesn't exist.
2. The OpenStackCluster becomes ready (provided no bastion is used or bastion is using an existing image)
3. There is no visible progress and no explanation for what is wrong at the OpenStackMachine level. Worse, there is a misleading message that the OpenStackMachine is waiting for bootstrap data, which is not true.
4. There is no explanation on the OpenStackServer. It is just "not ready"

**What did you expect to happen:**

There should be a condition on the OpenStackServer that would propagate to the OpenStackMachine, with a message explaining that the image cannot be found. The OpenStackMachine should not say that it is waiting for bootstrap data when the data is available.

**Anything else you would like to add:**

This issue is also present in v0.10, just that there is no OpenStackServer involved then.

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): v0.11.2
- Cluster-API version: v1.8.5
- OpenStack version:
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by lentzi90**
**What this PR does / why we need it**:

- Improve error and pending dependency reporting in server spec resolution
- Surface dependency errors and pending states as conditions on OpenStackServer
- Propagate OpenStackServer error and waiting states to OpenStackMachine
- Refactor ResolveServerSpec to return pending dependencies for better diagnostics

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2265

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**TODOs**:

- [x] squashed commits
- if necessary:
  - [ ] includes documentation
  - [ ] adds unit tests

/hold

### CODE REVIEW

File: controllers/openstackmachine_controller.go [hunk 1]
```diff
@@ -415,19 +425,34 @@ func (r *OpenStackMachineReconciler) reconcileNormal(ctx context.Context, scope
...
+			// Propagate the condition from OpenStackServer with its severity
+			v1beta1conditions.MarkFalse(openStackMachine, infrav1.InstanceReadyCondition, condition.Reason, condition.Severity, "%s", condition.Message)
+			v1beta1conditions.MarkFalse(openStackMachine, clusterv1beta1.ReadyCondition, condition.Reason, condition.Severity, "%s", condition.Message)
+			return &ctrl.Result{RequeueAfter: waitForBuildingInstanceToReconcile}
+		}
+
+		v1beta1conditions.MarkFalse(openStackMachine, infrav1.InstanceReadyCondition, infrav1.InstanceNotReadyReason, clusterv1beta1.ConditionSeverityInfo, "Waiting for instance to be created")
+		v1beta1conditions.MarkFalse(openStackMachine, clusterv1beta1.ReadyCondition, infrav1.InstanceNotReadyReason, clusterv1beta1.ConditionSeverityInfo, "Waiting for instance to be created")
+		return &ctrl.Result{RequeueAfter: waitForBuildingInstanceToReconcile}
+	}
```
[the remark this answers is not in the document]
Comment (lentzi90) [reply controllers/openstackmachine_controller.go:454]: Good bot! Fixed now.

File: controllers/openstackmachine_controller_test.go [hunk 2]
```diff
@@ -449,17 +449,87 @@ func TestGetPortIDs(t *testing.T) {
 func TestReconcileMachineState(t *testing.T) {
 	tests := []struct {
 		name                            string
-		instanceState                   infrav1.InstanceState
+		instanceState                   *infrav1.InstanceState
```
Comment (lentzi90) [inline controllers/openstackmachine_controller_test.go:452]: This was changed to pointer so that we can check the `nil` case...

**Comment by lentzi90** [comment]
Ok this is ready for review. There is a discussion in #2726 that may be of interest when reviewing. I did some manual tests and posted results there. This PR is then the result of addressing the findings.
/hold cancel

File: controllers/openstackmachine_controller_test.go [hunk 3]
```diff
@@ -449,17 +449,87 @@ func TestGetPortIDs(t *testing.T) {
...
+					Reason:   infrav1.DependencyFailedReason,
+					Message:  "Failed to resolve server spec: image not found",
+				},
+			},
+			expectRequeue: true,
+			expectedInstanceReadyCondition: &clusterv1beta1.Condition{
+				Type:     infrav1.InstanceReadyCondition,
+				Status:   corev1.ConditionFalse,
+				Severity: clusterv1beta1.ConditionSeverityError,
+				Reason:   infrav1.DependencyFailedReason,
```
Comment (mandre) [inline controllers/openstackmachine_controller_test.go:478]: Should we also check the Message?

File: controllers/openstackmachine_controller_test.go [hunk 4]
```diff
@@ -449,17 +449,87 @@ func TestGetPortIDs(t *testing.T) {
...
+			},
+			expectedReadyCondition: &clusterv1beta1.Condition{
+				Type:     clusterv1beta1.ReadyCondition,
+				Status:   corev1.ConditionFalse,
+				Severity: clusterv1beta1.ConditionSeverityInfo,
+				Reason:   infrav1.InstanceNotReadyReason,
+			},
+		},
+		{
+			name:          "Nil InstanceState with no server condition sets default waiting conditions",
```
Comment (mandre) [inline controllers/openstackmachine_controller_test.go:518]: This test effectively is identical to the `Nil InstanceState with InstanceNotReady condition propagates info to machine` case above, because we're not checking the Message.

File: controllers/openstackmachine_controller.go [hunk 5]
```diff
@@ -463,11 +488,19 @@ func (r *OpenStackMachineReconciler) reconcileMachineState(scope *scope.WithLogg
 		// If not, it is more likely a configuration error so we set failure and never retry.
 		scope.Logger().Info("Machine instance state is ERROR", "id", openStackServer.Status.InstanceID)
 		if !machine.Status.NodeRef.IsDefined() {
-			err := fmt.Errorf("instance state %v is unexpected", openStackServer.Status.InstanceState)
+			// Include the instance state in the error message for better debugging
+			err := fmt.Errorf("instance state is ERROR")
```
Comment (mandre) [inline controllers/openstackmachine_controller.go]: Wasn't the previous behavior clearer because it had the actual instance state, and not an hardcoded one?

File: controllers/openstackmachine_controller_test.go [hunk 6]
```diff
@@ -449,17 +449,87 @@ func TestGetPortIDs(t *testing.T) {
...
+				Severity: clusterv1beta1.ConditionSeverityInfo,
+				Reason:   infrav1.InstanceNotReadyReason,
+			},
+			expectedReadyCondition: &clusterv1beta1.Condition{
+				Type:     clusterv1beta1.ReadyCondition,
+				Status:   corev1.ConditionFalse,
+				Severity: clusterv1beta1.ConditionSeverityInfo,
+				Reason:   infrav1.InstanceNotReadyReason,
+			},
+		},
```
Comment (mandre) [inline controllers/openstackmachine_controller_test.go:535]: Should we also add a test for when the instance is in an Error state? This should propagate the error as well.

File: pkg/cloud/services/compute/referenced_resources.go [hunk 7]
```diff
@@ -37,7 +37,12 @@ import (
...
 // OpenStackServer is immutable, so we can't change the spec after the machine is created.
-func ResolveServerSpec(ctx context.Context, scope *scope.WithLogger, k8sClient client.Client, openStackServer *infrav1alpha1.OpenStackServer) (bool, bool, error) {
+// Returns: (changed, done, pendingDependencies, error)
+// - changed: true if the resolved spec was modified
+// - done: true if all dependencies are resolved
+// - pendingDependencies: list of dependency names that are not yet resolved (only meaningful when done=false and error=nil)
+// - error: any error that occurred during resolution.
+func ResolveServerSpec(ctx context.Context, scope *scope.WithLogger, k8sClient client.Client, openStackServer *infrav1alpha1.OpenStackServer) (bool, bool, []string, error) {
 	resolved := openStackServer.Status.Resolved
 	if resolved == nil {
```
Comment (bnallapeta) [inline pkg/cloud/services/compute/referenced_resources.go:47]: not your change. But this block is repeated again in lines 53-56

File: controllers/openstackmachine_controller.go (hunk 5 above)
Comment (bnallapeta) [reply controllers/openstackmachine_controller.go]: +1

Comment (lentzi90) [reply controllers/openstackmachine_controller.go]: Ah true, good find!

**Comment by lentzi90** [comment]
Thanks for the reviews! Good findings!
I think I have addressed them all now. PTAL :slightly_smiling_face:
