### PR TITLE
🐛 Fix panic when OpenStackCluster.Status.Network is nil in HCP scenarios

### LINKED ISSUE #2380: Panic in OpenStackMachineReconciler if OpenStackCluster.Status.Network is nil (Hosted Control Plane scenario)
/kind bug

**What steps did you take and what happened:**

In a “hosted control plane” setup (where the control plane runs outside of OpenStack, and only worker nodes are provisioned in OpenStack), OpenStackCluster.Status.Network can remain nil. Currently, the CAPO code in OpenStackMachineReconciler.getOrCreateMachineServer() assumes openStackCluster.Status.Network is always non-nil. This leads to a nil pointer dereference (panic) when calling:

```
machineServerSpec := openStackMachineSpecToOpenStackServerSpec(
    &openStackMachine.Spec,
    identityRef,
    compute.InstanceTags(&openStackMachine.Spec, openStackCluster),
    failureDomain,
    userDataRef,
    getManagedSecurityGroup(openStackCluster, machine),
    openStackCluster.Status.Network.ID,  // <- panic if .Network is nil
)
```

The controller then crashes, making it impossible to provision worker nodes.
- In HPC scenarios, there is no control-plane node running in OpenStack, so CAPO never populates OpenStackCluster.Status.Network.
- The machine reconciliation panics in openstackmachine_controller.go due to a nil pointer dereference on openStackCluster.Status.Network.ID.

Logs:

```
0116 03:44:55.377796       1 openstackmachine_controller.go:361] "Reconciling Machine" controller="openstackmachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="OpenStackMachine" OpenStackMachine="kcm-system/openstack-dev-hosted-cp-md-fcpqk-8l4q5" namespace="kcm-system" name="openstack-dev-hosted-cp-md-fcpqk-8l4q5" reconcileID="b00cfcbb-ae39-4bb9-aa87-0bcde7cb350d" openStackMachine="openstack-dev-hosted-cp-md-fcpqk-8l4q5" machine="openstack-dev-hosted-cp-md-fcpqk-8l4q5" cluster="openstack-dev-hosted-cp" openStackCluster="openstack-dev-hosted-cp"
I0116 03:44:55.378942       1 controller.go:110] "Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference" controller="openstackmachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="OpenStackMachine" OpenStackMachine="kcm-system/openstack-dev-hosted-cp-md-fcpqk-8l4q5" namespace="kcm-system" name="openstack-dev-hosted-cp-md-fcpqk-8l4q5" reconcileID="b00cfcbb-ae39-4bb9-aa87-0bcde7cb350d"
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1baafba]

goroutine 357 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.5/pkg/internal/controller/controller.go:111 +0x1e5
panic({0x1dccbe0?, 0x362a670?})
        /usr/local/go/src/runtime/panic.go:770 +0x132
sigs.k8s.io/cluster-api-provider-openstack/controllers.(*OpenStackMachineReconciler).getOrCreateMachineServer(0xc00043a2a0, {0x2440550, 0xc0005b7230}, 0xc0004deb08, 0xc0006bc508, 0xc0008fa008)
        /workspace/controllers/openstackmachine_controller.go:586 +0x35a
sigs.k8s.io/cluster-api-provider-openstack/controllers.(*OpenStackMachineReconciler).reconcileMachineServer(0x24467c8?, {0x2440550?, 0xc0005b7230?}, 0xc0006d1560, 0x13?, 0x0?, 0x0?)
        /workspace/controllers/openstackmachine_controller.go:544 +0x3d
sigs.k8s.io/cluster-api-provider-openstack/controllers.(*OpenStackMachineReconciler).reconcileNormal(0xc00043a2a0, {0x2440550, 0xc0005b7230}, 0xc0006d1560, {0xc000059500, 0x22}, 0xc0004deb08, 0xc0008fa008, 0xc0006bc508)
        /workspace/controllers/openstackmachine_controller.go:363 +0x178
sigs.k8s.io/cluster-api-provider-openstack/controllers.(*OpenStackMachineReconciler).Reconcile(0xc00043a2a0, {0x2440550, 0xc0005b7230}, {{{0xc0006b5576?, 0x0?}, {0xc00059d050?, 0xc0008f1d10?}}})
        /workspace/controllers/openstackmachine_controller.go:161 +0xbd8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x24467c8?, {0x2440550?, 0xc0005b7230?}, {{{0xc0006b5576?, 0xb?}, {0xc00059d050?, 0x0?}}})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.5/pkg/internal/controller/controller.go:114 +0xb7
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0004f2160, {0x2440588, 0xc00022f810}, {0x1e96420, 0xc00003d920})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.5/pkg/internal/controller/controller.go:311 +0x3bc
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0004f2160, {0x2440588, 0xc00022f810})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.5/pkg/internal/controller/controller.go:261 +0x1be
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.5/pkg/internal/controller/controller.go:222 +0x79
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2 in goroutine 203
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.5/pkg/internal/controller/controller.go:218 +0x486
```

**What did you expect to happen:**
That CAPO would handle the absence of status.network gracefully—e.g. by marking the OpenStackMachine with a condition or requeueing—rather than panicking.

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built):
- Cluster-API version:
- OpenStack version:
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by bnallapeta**
**What this PR does / why we need it**:
Fixes a nil pointer panic in OpenStackMachineReconciler when OpenStackCluster.Status.Network is nil, which occurs in Hosted Control Plane scenarios. The controller now gracefully handles missing cluster network by checking for nil before access and returning a terminal error instead of panicking. Also adds comprehensive HCP E2E test suite.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2380 

**TODOs**:

- [ ] squashed commits
- if necessary:
  - [ ] includes documentation
  - [ ] adds unit tests

/hold

### CODE REVIEW

**Comment by bnallapeta** [comment]
@EmilienM @mdbooth @lentzi90 

Marking it as Draft as we are working on the e2e tests. This is the approach being taken for e2e. Let me know your thoughts.

1. Spawn up a kind cluster -> turn it into a management cluster by installing CAPI/CAPO on it
2. Deploy a k8s cluster on OpenStack using this kind cluster. Let's call this Cluster A
3. Turn Cluster A into management cluster by installing CAPI/CAPO on it
4. Deploy a k8s cluster in the hosted control plane method using kamaji provider using cluster A. Let's call this Cluster B
5. Run the actual e2e tests to test out the panic case on Cluster B


Right now, we are somewhere in the 3rd/4th step and are facing the below challenges:

First, when we specify our Kamaji as a control plane provider in e2e_conf.yaml and name it as kamaji this error pops up:

```
[FAILED] The e2e test config file is not valid
Expected success, but got an error:
    <*errors.fundamental | 0xc000c00228>:
    invalid argument: invalid config: control-plane-provider should be named kubeadm
```

Second, if we try to bypass and name this kamaji as kubeadm, kamaji doesn't get installed as such and later on, we face issues with finding Kamaji CRDs

```
[FAILED] in [It] - /root/cluster-api-provider-openstack/test/e2e/suites/hcp/hcp_helpers.go:148 @ 07/31/25 11:01:25.32 < Exit [It] should create and manage HCP-capable cluster @ 07/31/25 11:01:25.32 (7m12.465s) << Timeline [FAILED] Timed out after 180.000s. Expected success, but got an error: <*apiutil.ErrResourceDiscoveryFailed | 0xc000123428>: unable to retrieve the complete list of server APIs: [kamaji.clastix.io/v1alpha1](http://kamaji.clastix.io/v1alpha1): no matches for [kamaji.clastix.io/v1alpha1](http://kamaji.clastix.io/v1alpha1), Resource= { { Group: "[kamaji.clastix.io](http://kamaji.clastix.io/)", Version: "v1alpha1", }: <*meta.NoResourceMatchError | 0xc0012143c0>{ PartialResource: { Group: "[kamaji.clastix.io](http://kamaji.clastix.io/)", Version: "v1alpha1", Resource: "", }, }, } In [It] at: /root/cluster-api-provider-openstack/test/e2e/suites/hcp/hcp_helpers.go:148 @ 07/31/25 11:01:25.32
```


Would really appreciate your help on this to move forward.

cc @orkhan-os

File: controllers/openstackmachine_controller.go [hunk 1]
```diff
@@ -588,7 +584,18 @@ func (r *OpenStackMachineReconciler) getOrCreateMachineServer(ctx context.Contex
...
+			// Determine default network ID if the cluster status exposes one.
+		var defaultNetworkID string
+		if openStackCluster.Status.Network != nil {
+			defaultNetworkID = openStackCluster.Status.Network.ID
+		}
+
+		// If no cluster network is available AND the machine spec did not define any ports with a network, we cannot choose a network.
+		if defaultNetworkID == "" && len(openStackMachine.Spec.Ports) == 0 {
+			return nil, capoerrors.Terminal(infrav1.InvalidMachineSpecReason, "no network configured: cluster network is missing and machine spec does not define ports with a network")
+		}
```
Comment (mdbooth) [inline controllers/openstackmachine_controller.go]: nit: I feel like this splits this logic across this function and `openStackMachineSpecToOpenStackServerSpec`. Did you consider putting this logic in  `openStackMachineSpecToOpenStackServerSpec` and modifying its signature to return an error?

File: controllers/openstackmachine_controller_test.go [hunk 2]
```diff
@@ -158,27 +155,67 @@ func TestOpenStackMachineSpecToOpenStackServerSpec(t *testing.T) {
...
+        },
 	}
 	for i := range tests {
 		tt := tests[i]
 		t.Run(tt.name, func(t *testing.T) {
-			spec := openStackMachineSpecToOpenStackServerSpec(tt.spec, identityRef, tags, "", userData, &openStackCluster.Status.WorkerSecurityGroup.ID, openStackCluster.Status.Network.ID)
+			defaultNetID := ""
+			if openStackCluster.Status.Network != nil {
+				defaultNetID = openStackCluster.Status.Network.ID
+			}
```
Comment (mdbooth) [inline controllers/openstackmachine_controller_test.go]: More evidence of what I was saying above:  this duplicates part of the functionality in the test. If we did this in `openStackMachineSpecToOpenStackServerSpec` we could just test it.

File: docs/book/src/development/development.md [hunk 3]
```diff
@@ -562,3 +562,5 @@ kubectl get openstackservers
 ```
 
 This object is immutable and is created by the controller when a machine or a bastion is created. The `OpenStackServer` object is deleted when the machine or the bastion is deleted.
+
+
```
Comment (mdbooth) [inline docs/book/src/development/development.md]: ?

File: pkg/cloud/services/networking/securitygroups.go [hunk 4]
```diff
@@ -564,6 +565,11 @@ func (s *Service) createRule(securityGroupID string, r resolvedSecurityGroupRule
 	s.scope.Logger().V(6).Info("Creating rule", "description", r.Description, "direction", dir, "portRangeMin", r.PortRangeMin, "portRangeMax", r.PortRangeMax, "proto", proto, "etherType", etherType, "remoteGroupID", r.RemoteGroupID, "remoteIPPrefix", r.RemoteIPPrefix, "securityGroupID", securityGroupID)
 	_, err := s.client.CreateSecGroupRule(createOpts)
 	if err != nil {
+		// Handle HTTP 409 (SecurityGroupRuleExists) as success - the rule already exists
+		if strings.Contains(err.Error(), "SecurityGroupRuleExists") || strings.Contains(err.Error(), "already exists") {
+			s.scope.Logger().V(4).Info("Security group rule already exists, treating as success", "description", r.Description, "securityGroupID", securityGroupID)
+			return nil
+		}
```
Comment (mdbooth) [inline pkg/cloud/services/networking/securitygroups.go]: This looks unrelated? Separate PR, perhaps?

**Review by mdbooth — COMMENTED** [review]
Appreciate this is just a draft, but I had a quick look over it anyway.

File: controllers/openstackmachine_controller.go (hunk 1 above)
Comment (bnallapeta) [reply controllers/openstackmachine_controller.go]: Done. Code is updated.

File: controllers/openstackmachine_controller_test.go (hunk 2 above)
Comment (bnallapeta) [reply controllers/openstackmachine_controller_test.go:228]: Done.

File: docs/book/src/development/development.md (hunk 3 above)
Comment (bnallapeta) [reply docs/book/src/development/development.md]: Its fixed now.

File: pkg/cloud/services/networking/securitygroups.go (hunk 4 above)
Comment (bnallapeta) [reply pkg/cloud/services/networking/securitygroups.go]: I came across this issue while I was testing the PR. It won't work without this change.

But sure, I can open another one and then rebase this later on.

File: controllers/openstackmachine_controller.go (hunk 1 above)
Comment (bnallapeta) [reply controllers/openstackmachine_controller.go]: Done.

File: controllers/openstackmachine_controller_test.go (hunk 2 above)
Comment (bnallapeta) [reply controllers/openstackmachine_controller_test.go]: Done.

File: controllers/openstackmachine_controller_test.go [hunk 5]
```diff
@@ -174,12 +172,99 @@ func TestOpenStackMachineSpecToOpenStackServerSpec(t *testing.T) {
...
+			case tt.name == "Empty cluster network ID, machine defines explicit ports":
+				// Create a cluster network with empty ID
+				clusterNetwork = &infrav1.NetworkStatusWithSubnets{
+					NetworkStatus: infrav1.NetworkStatus{
+						ID: "", // Empty network ID
+					},
+				}
+			default:
+				clusterNetwork = openStackCluster.Status.Network
+			}
```
Comment (mdbooth) [inline controllers/openstackmachine_controller_test.go]: My personal preference would be to include this directly in the tests somehow. Makes it easier to read. One of us has made an error in the test definitions above, and I think it would be easier to spot of they were all together.

File: controllers/openstackmachine_controller_test.go [hunk 6]
```diff
@@ -174,12 +172,99 @@ func TestOpenStackMachineSpecToOpenStackServerSpec(t *testing.T) {
 				UserDataRef: userData,
 			},
 		},
+		{
+			name: "Cluster network nil, machine defines port network and overrides SG",
```
Comment (mdbooth) [inline controllers/openstackmachine_controller_test.go:184]: Why is cluster network nil in this test? Looks like it would be set on line 60, copied by line 259?

File: controllers/openstackmachine_controller_test.go [hunk 7]
```diff
@@ -174,12 +172,99 @@ func TestOpenStackMachineSpecToOpenStackServerSpec(t *testing.T) {
...
+				Ports: []infrav1.PortOpts{{
+					Network:        &infrav1.NetworkParam{ID: ptr.To(networkUUID)},
+					SecurityGroups: []infrav1.SecurityGroupParam{{ID: ptr.To(extraSecurityGroupUUID)}},
+				}},
+				Tags:        tags,
+				UserDataRef: userData,
+			},
+		},
+		{
+			name: "Cluster network nil, machine defines port network and falls back to cluster SG",
```
Comment (mdbooth) [inline controllers/openstackmachine_controller_test.go:206]: Ditto.

File: controllers/openstackmachine_controller_test.go (hunk 6 above)
Comment (bnallapeta) [reply controllers/openstackmachine_controller_test.go:184]: Addressed.

File: controllers/openstackmachine_controller_test.go (hunk 5 above)
Comment (bnallapeta) [reply controllers/openstackmachine_controller_test.go]: The reason I did it this way is to avoid duplication of code and avoid passing `clusterNetwork` to each and every case. I was going for minimal changes to existing code. 

But sure, since we don't want use `switch`, I have removed it entirely and included `clusterNetwork` as a field in the tests struct.

File: controllers/openstackmachine_controller_test.go (hunk 7 above)
Comment (bnallapeta) [reply controllers/openstackmachine_controller_test.go:206]: Addressed.

File: controllers/openstackmachine_controller_test.go (hunk 6 above)
Comment (bnallapeta) [reply controllers/openstackmachine_controller_test.go:184]: This one and the next one is supposed to have cluster network set to nil. And it is explicitly done now in line 188.

File: controllers/openstackmachine_controller_test.go [hunk 8]
```diff
@@ -82,9 +82,6 @@ func TestOpenStackMachineSpecToOpenStackServerSpec(t *testing.T) {
 				ID: ptr.To(openStackCluster.Status.Network.ID),
 			},
 			SecurityGroups: []infrav1.SecurityGroupParam{
-				{
-					ID: ptr.To(openStackCluster.Status.WorkerSecurityGroup.ID),
-				},
```
Comment (lentzi90) [inline controllers/openstackmachine_controller_test.go]: Why was this removed? Do we have a change in behavior for the security groups?

File: controllers/openstackmachine_controller.go [hunk 9]
```diff
@@ -522,25 +533,21 @@ func openStackMachineSpecToOpenStackServerSpec(openStackMachineSpec *infrav1.Ope
...
-			}
+		// Only inject the default network when we actually have an ID.
+		if serverPorts[i].Network == nil && defaultNetworkID != "" {
+			serverPorts[i].Network = &infrav1.NetworkParam{ID: &defaultNetworkID}
 		}
 		if len(openStackMachineSpec.SecurityGroups) > 0 {
-			serverPorts[i].SecurityGroups = append(serverPorts[i].SecurityGroups, openStackMachineSpec.SecurityGroups...)
+			// Machine level security groups override any cluster defaults.
+			serverPorts[i].SecurityGroups = openStackMachineSpec.SecurityGroups
+		} else if len(serverPorts[i].SecurityGroups) == 0 && defaultSecGroup != nil {
```
Comment (lentzi90) [inline controllers/openstackmachine_controller.go]: I think this is a change in behavior. Previously, we set the defaultSecGroup and then appended security groups from the OSM. Now we are taking the security groups from the OSM *instead* of the defaultSecGroup.

**Review by lentzi90 — COMMENTED** [review]
Am I understanding correctly that this changes the behavior for security groups on OpenStackMachines? We cannot sneak in that change as a bug fix (🐛 ). If we want to change it (and I am not sure we do), the PR has to be marked as a breaking change (⚠️ ).

File: controllers/openstackmachine_controller_test.go (hunk 8 above)
Comment (bnallapeta) [reply controllers/openstackmachine_controller_test.go]: This was due to the other change. Its fixed.

File: controllers/openstackmachine_controller.go (hunk 9 above)
Comment (bnallapeta) [reply controllers/openstackmachine_controller.go]: You're right, good catch! 

I think we don't have to change the securityGroup logic. The change done to handle the network is enough to cover all scenarios. I have reverted it and now the PR only shows the network change to handle the nil pointer panic caused in Hosted CP scenarios.

File: docs/book/src/topics/hosted-control-plane.md [hunk 10]
```diff
@@ -0,0 +1,449 @@
...
+- A healthy Kubernetes cluster with cluster-admin access
+- Cluster API initialized with the OpenStack infrastructure provider:
+  ```bash
+  clusterctl init --infrastructure openstack
+  ```
+- k0smotron installed (docs: https://docs.k0smotron.io/stable/install/#software-prerequisites)
+- A LoadBalancer implementation for the hosted control plane service (OpenStack CCM/Octavia or MetalLB)
+- OpenStack Cinder CSI driver installed and operational on the management cluster with:
+  - Valid OpenStack credentials secret in the `kube-system` namespace
+  - A default StorageClass configured (if you install the openstack-cinder-csi helm chart, then the StorageClass will be created for you)
```
Comment (lentzi90) [inline docs/book/src/topics/hosted-control-plane.md]: Let's make this also generic, similar to the point above.

```suggestion
- A storage solution for etcd, e.g. OpenStack Cinder CSI driver, including a default StorageClass (if you install the openstack-cinder-csi helm chart, then the StorageClass will be created for you).
```

File: docs/book/src/topics/hosted-control-plane.md [hunk 11]
```diff
@@ -0,0 +1,449 @@
...
+```bash
+base64 -w0 clouds.yaml > clouds.yaml.b64
+```
+
+**macOS:**
+```bash
+base64 -b0 clouds.yaml > clouds.yaml.b64
+```
+
+Copy the single-line contents of `clouds.yaml.b64` and paste it into the cluster manifest at `data.clouds.yaml` (replace `<BASE64_OF_clouds.yaml_HERE>`).
```
Comment (lentzi90) [inline docs/book/src/topics/hosted-control-plane.md]: Let's simplify this. We can create the secret directly instead of first encoding and then copying into the manifests.

```suggestion
Create a secret with credentials for the tenant cluster external cloud provider. The cluster manifest expects a secret named `openstack-cloud-config` in the `hcp-system` namespace with a `clouds.yaml` key.

Create the secret directly from your `clouds.yaml` file like this:

```bash
kubectl -n hcp-system create secret generic openstack-cloud-config \
  --from-file=clouds.yaml=./clouds.yaml
```
```

File: docs/book/src/topics/hosted-control-plane.md [hunk 12]
```diff
@@ -0,0 +1,449 @@
...
+```yaml
+apiVersion: v1
+data:
+  cacert: null
+  clouds.yaml: <BASE64_OF_clouds.yaml_HERE>
+kind: Secret
+metadata:
+  name: openstack-cloud-config
+  namespace: hcp-system
+---
```
Comment (lentzi90) [inline docs/book/src/topics/hosted-control-plane.md]: With the secret created above, this is no longer needed.

```suggestion
```

File: docs/book/src/topics/hosted-control-plane.md [hunk 13]
```diff
@@ -0,0 +1,449 @@
...
+```
+
+**macOS:**
+```bash
+base64 -b0 clouds.yaml > clouds.yaml.b64
+```
+
+Copy the single-line contents of `clouds.yaml.b64` and paste it into the cluster manifest at `data.clouds.yaml` (replace `<BASE64_OF_clouds.yaml_HERE>`).
+
+### 2. Install Cinder CSI on Management Cluster
```
Comment (lentzi90) [inline docs/book/src/topics/hosted-control-plane.md]: This step feels a bit strange to me. We don't show how to setup the cloud controller manager or metallb, so why show the cinder CSI? I would say we should either show all of it or we just skip this step.

File: docs/book/src/topics/hosted-control-plane.md [hunk 14]
```diff
@@ -0,0 +1,449 @@
...
+kubectl -n kube-system get pods | grep -i cinder
+kubectl get sc
+```
+
+### 3. Configure and Deploy the Cluster
+
+Before applying the manifests, update the following fields:
+
+- Update network, router, and subnet names in `OpenStackCluster` and `OpenStackMachineTemplate` to match your OpenStack environment
+- Insert the base64-encoded `clouds.yaml` content prepared in step 1
```
Comment (lentzi90) [inline docs/book/src/topics/hosted-control-plane.md]:
```suggestion
```

File: docs/book/src/topics/hosted-control-plane.md [hunk 15]
```diff
@@ -0,0 +1,449 @@
...
+
+## Post-Deployment Configuration
+
+### Retrieve Tenant Cluster Access
+
+Obtain the tenant cluster kubeconfig:
+
+```bash
+kubectl -n hcp-system get secrets | grep -i kubeconfig
+kubectl -n hcp-system get secret <NAME> -o jsonpath='{.data.value}' | base64 -d > tenant.kubeconfig
```
Comment (lentzi90) [inline docs/book/src/topics/hosted-control-plane.md]:
```suggestion
clusterctl -n hcp-system get kubeconfig openstack-hcp-cluster > tenant.kubeconfig
```

File: docs/book/src/topics/hosted-control-plane.md [hunk 16]
```diff
@@ -0,0 +1,449 @@
...
+## Conclusion
+
+This guide demonstrated how to deploy a Kubernetes cluster on OpenStack using a hosted control plane architecture with Cluster API Provider OpenStack (CAPO) and k0smotron. The key benefits of this approach include:
+
+### Advantages of Hosted Control Planes
+
+- **Resource Efficiency**: Control plane components run as pods on the management cluster, reducing the infrastructure footprint
+- **Simplified Management**: Centralized control plane management across multiple tenant clusters
+- **High Availability**: Leverages the management cluster's infrastructure for control plane resilience
+- **Cost Optimization**: Eliminates the need for dedicated control plane nodes in each tenant cluster
```
Comment (lentzi90) [inline docs/book/src/topics/hosted-control-plane.md]: I would suggest putting this at the top instead of here at the bottom. People may want to know the benefits before going through the whole example 🙂

File: docs/book/src/topics/hosted-control-plane.md (hunk 13 above)
Comment (bnallapeta) [reply docs/book/src/topics/hosted-control-plane.md]: OpenStack ccm or Metallb - loadbalancer is an optional thing. But to keep it production-style, the manifests include `LoadBalancer` in the `K0smotronControlPlane` and thus we ask the users to setup whatever load balancer they like. 
(Furthermore, if someone knows what they're doing, they can remove this block and use ClusterIP or NodePort to keep it all local.)

But Cinder CSI is a mandatory requirement in order to schedule the control plane pods on the management cluster which includes the etcd. Without storage in place on the management cluster, hosted cp cluster deployment will fail. And since we are working with OpenStack, I chose to show Cinder CSI.

File: docs/book/src/topics/hosted-control-plane.md (hunk 14 above)
Comment (bnallapeta) [reply docs/book/src/topics/hosted-control-plane.md]: Done.

File: docs/book/src/topics/hosted-control-plane.md (hunk 15 above)
Comment (bnallapeta) [reply docs/book/src/topics/hosted-control-plane.md]: Done.

File: docs/book/src/topics/hosted-control-plane.md (hunk 16 above)
Comment (bnallapeta) [reply docs/book/src/topics/hosted-control-plane.md]: Done.

File: docs/book/src/topics/hosted-control-plane.md (hunk 12 above)
Comment (bnallapeta) [reply docs/book/src/topics/hosted-control-plane.md]: Done.

File: docs/book/src/topics/hosted-control-plane.md (hunk 11 above)
Comment (bnallapeta) [reply docs/book/src/topics/hosted-control-plane.md]: Done.

File: docs/book/src/topics/hosted-control-plane.md (hunk 10 above)
Comment (bnallapeta) [reply docs/book/src/topics/hosted-control-plane.md]: Done.

**Comment by bnallapeta** [comment]
@lentzi90 addressed all the comments on docs. Just one conversation yet to be resolved. 

Also, with this commit, I updated all references of tenant cluster to workload cluster to stay in touch with CAPI/CAPO nomenclature.

File: docs/book/src/topics/hosted-control-plane.md (hunk 13 above)
Comment (lentzi90) [reply docs/book/src/topics/hosted-control-plane.md]: Well, I would say Cinder is just as optional as the LoadBalancer. In this example we use it, but a user that knows what they are doing could be using Ceph or the local-path provisioner if they want. But I'm not saying there is any issue with showing Cinder here, it just feels strange to show how to install that but not the CCM.

Honestly, I have never installed Cinder CSI separate from the CCM so seeing one here without the other feels strange. Perhaps it is normal to do it this way and I'm just weird :joy: 
For reference, this is what I usually do: https://github.com/lentzi90/playground/blob/main/ClusterResourceSets/cloud-provider-openstack/kustomization.yaml
Just one kustomization with all of it.

Comment (bnallapeta) [reply docs/book/src/topics/hosted-control-plane.md]: Kinda agree with you. So, what do you prefer? include both instructions? or remove this? I'd prefer we keep it so that the guide will feel "complete".

File: controllers/openstackmachine_controller.go (hunk 9 above)
Comment (mdbooth) [reply controllers/openstackmachine_controller.go]: Nice catch!
