### PR TITLE
:bug: Fix Provisioning to Unavailable AZs

### LINKED ISSUE #1477: AZ Availabilty Not Being Checked
/kind bug

**What steps did you take and what happened:**

https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/02a31730ef1ae7962f1cc36c090b624025a2f5bc/pkg/cloud/services/compute/availabilityzone.go#L25 or https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/f4e61b626eec3c5eb82e5f3328de0da6fe1d540d/pkg/clients/compute.go#L79 don't filter out unavailable availability zones.

**What did you expect to happen:**

It filters unavailable zones out so the control plane etc. gets scheduled on an available AZ.

**Anything else you would like to add:**

We could/should work around this problem by explicitly stating the AZs in the OSC resource, but that's not available to us as we punt everything through a single Helm chart, adding the field gets rejected because of the validating webhook for existing clusters.  If we try to switch the OSC out with a new one, that gets really broken as it tries to allocate a new VIP on the load balancer, fails as the old one is in place, uses up all the floating IPs on the platform in the process.  Disassociating the VIP to lend a helping hand is even worse because everything loses the ability to talk to the API.  Non fun 😸 

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built):
- Cluster-API version:
- OpenStack version:
- Minikube/KIND version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by spjmurray**
CAPO uses any ZA it finds, rather than checking whether the ZA is actually available, meaning you can get into a state where it's impossible to provision a cluster.  This allows clients to filter based on AZ availability before scheduling.

Fixes #1477

**What this PR does / why we need it**:

Discussion in #1477 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**TODOs**:

- [x ] squashed commits
- if necessary:
  - [ ] includes documentation
  - [ ] adds unit tests

/hold

### CODE REVIEW

**Review by lentzi90 — COMMENTED** [review]
/ok-to-test

File: pkg/cloud/services/compute/availabilityzone.go [hunk 1]
```diff
@@ -30,3 +30,21 @@ func (s *Service) GetAvailabilityZones() ([]availabilityzones.AvailabilityZone,
 
 	return availabilityZoneList, nil
 }
+
+// GetAvailableAvailabilityZones does as it says, but only returns usable AZs.
+func (s *Service) GetAvailableAvailabilityZones() ([]availabilityzones.AvailabilityZone, error) {
+        availabilityZoneList, err := s.getComputeClient().ListAvailabilityZones()
```
Comment (lentzi90) [inline pkg/cloud/services/compute/availabilityzone.go:36]: Maybe slightly better to use the function above. Just a suggestion
```suggestion
        availabilityZoneList, err := s.GetAvailabilityZones()
```

File: api/v1alpha6/openstackcluster_webhook.go [hunk 2]
```diff
@@ -115,6 +115,10 @@ func (r *OpenStackCluster) ValidateUpdate(oldRaw runtime.Object) error {
 		r.Spec.APIServerLoadBalancer.AllowedCIDRs = []string{}
 	}
 
+	// Allow changes to the availability zones.
+	old.Spec.ControlPlaneAvailabilityZones = []string{}
+	r.Spec.ControlPlaneAvailabilityZones = []string{}
+
```
Comment (mdbooth) [inline api/v1alpha6/openstackcluster_webhook.go:121]: Whoops! That's quite an oversight.

Please could you add unit tests for these to `openstackcluster_webhook_test.go`?

File: pkg/cloud/services/compute/availabilityzone.go [hunk 3]
```diff
@@ -30,3 +30,21 @@ func (s *Service) GetAvailabilityZones() ([]availabilityzones.AvailabilityZone,
 
 	return availabilityZoneList, nil
 }
+
+// GetAvailableAvailabilityZones does as it says, but only returns usable AZs.
+func (s *Service) GetAvailableAvailabilityZones() ([]availabilityzones.AvailabilityZone, error) {
```
Comment (mdbooth) [inline pkg/cloud/services/compute/availabilityzone.go:35]: Couple of things:

Firstly there's only 1 caller of GetAvailabilityZones() and this PR replaces it with a call to this new function, leaving the old one as dead code. We should just modify GetAvailabilityZones() to do what we want.

Secondly, I'm wondering what the impact of removing the FD from cluster.Status.FailureDomains will be in the context of https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1466. In that PR I'm modifying the machine controller to actually look up the failure domain on first use. With this change, if a MachineDeployment referenced an AZ which became unavailable, the cluster controller would eventually delete it. Prior to that the machine would be created but would be unschedulable and enter the ERROR state. After that the machine controller would refuse to create it in the first place and enter a backoff loop waiting for it to exist.

Meh, don't worry about the second one: it's not in scope of your PR. In general, it points out that we have some baked assumptions about AZs being static that aren't necessarily true. We should likely ensure that the cluster controller runs periodically even without k8s watch events. Perhaps every 10 minutes or so.

**Review by mdbooth — CHANGES_REQUESTED** [review]
Looks good in principal. Just need to update the unit tests for the webhook change and to avoid creating dead code in availabilityzones.go.

File: pkg/cloud/services/compute/availabilityzone.go (hunk 3 above)
Comment (spjmurray) [reply pkg/cloud/services/compute/availabilityzone.go:35]: I figured it best to leave both versions, then the caller man make the decision whether they want to consider available ones, or not.  Combining the two views you can derive either {available, not available, non-existent}.  But I'm happy to clean up.

I thought the AZ mutability would possibly raise some eye-brows 😄  I figured, seeing as it's implicitly refreshed every reconcile, then technically speaking it's already mutable, which as you say reacts nicely to AZs vanishing.

File: api/v1alpha6/openstackcluster_webhook.go (hunk 2 above)
Comment (spjmurray) [reply api/v1alpha6/openstackcluster_webhook.go:121]: roger!

File: pkg/cloud/services/compute/availabilityzone.go (hunk 1 above)
Comment (spjmurray) [reply pkg/cloud/services/compute/availabilityzone.go]: Followed Matt's advice below.

**Comment by mdbooth** [comment]
/approve

Thanks! I'll leave lgtm to another reviewer.

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Comment by mdbooth** [comment]
@spjmurray If you cancel the hold this will merge.
