### PR TITLE
✨Add Octavia OVN Provider Support

### LINKED ISSUE #1472: Flag `--lb-provider=ovn` does not work properly when set.
/kind bug

**What steps did you take and what happened:**
It does not seem that the `provider id` is being set, when flag `--lb-provider=ovn` is being sent properly to octavia api.

ERROR:
```json
I0212 19:02:55.248980       1 loadbalancer.go:167] "Creating load balancer in subnet: \"91402434-8ba8-4304-a81a-0a302b163a2c\"" controller="openstackcluster" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="OpenStackCluster" OpenStackCluster="openstack/mgt" namespace="openstack" reconcileID=94399840-66bc-4e7a-b461-99e1db6e3275 cluster="mgt" name="k8s-clusterapi-cluster-openstack-mgt-kubeapi"
I0212 19:02:55.249069       1 provider.go:127] OpenStack Request URL: POST https://SOME-OPENSTACK-URL.com:9876/v2.0/lbaas/loadbalancers
I0212 19:02:55.249086       1 provider.go:127] OpenStack Request Headers:
Accept: application/json
Content-Type: application/json
User-Agent: gophercloud/2.0.0
X-Auth-Token: ***
I0212 19:02:55.249120       1 provider.go:127] OpenStack Request Body: {
  "loadbalancer": {
    "description": "Created by cluster-api-provider-openstack cluster openstack-mgt",
    "name": "k8s-clusterapi-cluster-openstack-mgt-kubeapi",
    "vip_subnet_id": "91402434-8ba8-4304-a81a-0a302b163a2c"
  }
}
I0212 19:02:56.833037       1 provider.go:127] OpenStack Response Code: 400
I0212 19:02:56.833080       1 provider.go:127] OpenStack Response Headers:
Content-Length: 95
Content-Type: application/json
Date: Sun, 12 Feb 2023 19:02:55 GMT
Server: Apache/2.4.52 (Ubuntu)
X-Openstack-Request-Id: req-39f960f4-27a6-43f7-9287-c28f0077db2b
I0212 19:02:56.833144       1 provider.go:127] OpenStack Response Body: {
  "debuginfo": null,
  "faultcode": "Client",
  "faultstring": "Provider 'amphora' is not enabled."
}
I0212 19:02:56.833577       1 recorder.go:103] "events: Failed to create load balancer k8s-clusterapi-cluster-openstack-mgt-kubeapi: Bad request with: [POST https://SOME-OPENSTACK-URL.com:9876/v2.0/lbaas/loadbalancers], error message: {\"faultcode\": \"Client\", \"faultstring\": \"Provider 'amphora' is not enabled.\", \"debuginfo\": null}" type="Warning" object={Kind:OpenStackCluster Namespace:openstack Name:mgt UID:a0411a15-0ab0-4472-998b-588cc4e3fe7a APIVersion:infrastructure.cluster.x-k8s.io/v1alpha6 ResourceVersion:5154 FieldPath:} reason="Failedcreateloadbalancer"
I0212 19:02:56.833601       1 request.go:1073] Request Body: {"count":15,"lastTimestamp":"2023-02-12T19:02:56Z","message":"Failed to create load balancer k8s-clusterapi-cluster-openstack-mgt-kubeapi: Bad request with: [POST https://SOME-OPENSTACK-URL.com:9876/v2.0/lbaas/loadbalancers], error message: {\"faultcode\": \"Client\", \"faultstring\": \"Provider 'amphora' is not enabled.\", \"debuginfo\": null}"}
```

I believe the issue is in the `POST` not providing the key `provider` correctly.
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/61a1650d39faba33348f7a57ccca4f7868ff1d05/pkg/cloud/services/loadbalancer/loadbalancer.go#L170-L177

Adding the following to `octavia.conf` file fixes this issue.
```toml
[api_settings]
bind_host = 10.30.0.4
bind_port = 9876
enabled_provider_drivers = amphora:Amphora provider, ovn:OVN provider
default_provider_driver = ovn
```

Additionally,
Per OVN docs, flag `LBMethodRoundRobin `, is not a valid function that is currently supported.

[Docs](https://docs.openstack.org/ovn-octavia-provider/latest/admin/driver.html#limitations-of-the-ovn-provider-driver)

ISSUE: (value is not configurable):
https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/61a1650d39faba33348f7a57ccca4f7868ff1d05/pkg/cloud/services/loadbalancer/loadbalancer.go#L318

ERROR:
```json
I0212 19:30:12.521139       1 http.go:143] "controller-runtime/webhook/webhooks: wrote response" webhook="/validate-infrastructure-cluster-x-k8s-io-v1alpha6-openstackcluster" code=200 reason= UID=c9df0d5b-58b3-4b51-bb33-810c9619658f allowed=true
E0212 19:30:12.532814       1 controller.go:326] "Reconciler error" err=<
	failed to reconcile load balancer: Expected HTTP response code [201 202] when accessing [POST https:///SOME-OPENSTACK-URL.comx:9876/v2.0/lbaas/pools], but got 501 instead
	{"faultcode": "Server", "faultstring": "Provider 'ovn' does not support a requested option: OVN provider does not support ROUND_ROBIN algorithm", "debuginfo": null}
```

Seems something would need to be done to automatically detect the feature flag is being used and change the option to 
`LBMethodSourceIp`, preferably this would be a flag that can be changed via a CRD option, verus a flag that cannot be dynamically changed.`OpenStackCluster.spec.apiServerLoadBalancer.provider`

Example CRD:
```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha6
kind: OpenStackCluster
metadata:
  name: mgt
  namespace: openstack
spec:
  apiServerLoadBalancer:
    enabled: true
    provider: ovn
```

**What did you expect to happen:**
When `lb-provider=ovn` is enabled users will be able to create clusters properly.

**Environment:**

- Cluster API Provider OpenStack version (Or `git rev-parse HEAD` if manually built): v7.0.0
- Cluster-API version: 1.3.3
- OpenStack version: zed
- Kubernetes version (use `kubectl version`): v1.25.4
- OS (e.g. from `/etc/os-release`): flatcar / ubuntu 2004

### PR DESCRIPTION
**Pull request by ching-kuo**
**What this PR does / why we need it**:

This commit adds support for Octavia OVN Provider. Changes includes adding provider option in apiServerLoadBalancer and when it is set to OVN, use SOURCE_IP_PORT as load balancing algorithm.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1472 

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**TODOs**:

- [x] squashed commits
- if necessary:
  - [ ] includes documentation
  - [ ] adds unit tests

### CODE REVIEW

**Comment by ching-kuo** [comment]
@jichenjc `zz_generated.conversion.go` files are generated by `make generate`, should I manually modify them? Seems like tests are failing at the conversions part.

**Comment by lentzi90** [comment]
> @jichenjc `zz_generated.conversion.go` files are generated by `make generate`, should I manually modify them? Seems like tests are failing at the conversions part.

You don't have touch the `zz_generated.conversion.go` files, but you will need to make some manual changes in `conversion.go` files. If you check the `zz_generated.conversion.go` file, it added a comment about what you need to do. See here: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1501/files#diff-61ccb8c68af6cd0480e4ad1b5310c95e6cfc2f533c7f633f83cfee76d4d596d0

**Comment by ching-kuo** [comment]
CI failed at converting for `v1alpha3` and `v1alpha4`, `make generate` only generates conversion for `v1alpha5` and `v1alpha6`. Is this expected?

**Comment by lentzi90** [comment]
> CI failed at converting for `v1alpha3` and `v1alpha4`, `make generate` only generates conversion for `v1alpha5` and `v1alpha6`. Is this expected?

Strange. It should do it for all: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/Makefile#L263-L270
But maybe there was no needed changes in the generated code for v1alpha3 and v1alpha4? So if you add the same things you did for v1alpha5 and v1alpha6 to `conversion.go` I think it should work.

File: pkg/cloud/services/loadbalancer/loadbalancer.go [hunk 1]
```diff
@@ -71,6 +71,8 @@ func (s *Service) ReconcileLoadBalancer(openStackCluster *infrav1.OpenStackClust
 		if v.Name == defaultLoadBalancerProvider {
 			lbProvider = v.Name
 			break
+		} else {
+			lbProvider = openStackCluster.Spec.APIServerLoadBalancer.Provider
```
Comment (jichenjc) [inline pkg/cloud/services/loadbalancer/loadbalancer.go:75]: this will still choose amphora? 
should we check whether it's enabled in backend then use it (otherwise error out)
if not given, then use default one?

**Comment by mdbooth** [comment]
@dulek Are you able to review this?

**Review by dulek — CHANGES_REQUESTED** [review]
Request in comment above.

File: pkg/cloud/services/loadbalancer/loadbalancer.go [hunk 2]
```diff
@@ -64,11 +64,15 @@ func (s *Service) ReconcileLoadBalancer(openStackCluster *infrav1.OpenStackClust
 		return err
 	}
 
-	// As mostly all LoadBalancer features are only supported on "amphora" we explicitly set the provider
-	// in the LoadBalancer create call to make sure to get the desired features - even if multiple providers exist.
+	// Choose the selected provider if it is set in cluster spec, if not we explicitly set the provider to "amphora"
```
Comment (mdbooth) [inline pkg/cloud/services/loadbalancer/loadbalancer.go:67]: See above comment about this. Should this be 'Amphora' or can we reasonably not specify anything and let Octavia pick? I don't know enough (at least not yet) to pick, but I would like to know that it we have considered the options and made a deliberate choice.

**Review by mdbooth — COMMENTED** [review]
Looks good in principal, thanks! I would like to ensure we're careful about the API change, though, even a relatively simple one like this.

File: pkg/cloud/services/loadbalancer/loadbalancer.go (hunk 2 above)
Comment (ching-kuo) [reply pkg/cloud/services/loadbalancer/loadbalancer.go:67]: I believe there is a `default_provider_driver` setting in Octavia defaults to `amphora`.
https://docs.openstack.org/octavia/latest/configuration/configref.html

IMO, it's reasonable to leave it empty and let Octavia use its default provider

File: api/v1alpha7/types.go [hunk 3]
```diff
@@ -323,6 +323,8 @@ type APIServerLoadBalancer struct {
 	AdditionalPorts []int `json:"additionalPorts,omitempty"`
 	// AllowedCIDRs restrict access to all API-Server listeners to the given address CIDRs.
 	AllowedCIDRs []string `json:"allowedCidrs,omitempty"`
+	// Octavia Provider Used to create load balancer
+	Provider string `json:"provider,omitempty"`
```
[the remark this answers is not in the document]
Comment (mdbooth) [reply api/v1alpha7/types.go:327]: @ching-kuo based on @dulek's points above please ignore my suggestion. It sounds like freeform is the only practical option here.

File: pkg/cloud/services/loadbalancer/loadbalancer.go (hunk 2 above)
Comment (mdbooth) [reply pkg/cloud/services/loadbalancer/loadbalancer.go:67]: If Octavia has its own default I prefer to use that rather than encode our own.

**Comment by dulek** [comment]
> > This looks pretty good, but older versions of OVN Octavia provider do not support health monitors. You got to skip creation of the health monitor for the poolby adding a call to `IsOctaviaFeatureSupported`. It's not directly stated, but I think you can test for v2.24 as a version that supports health monitors on OVN provider (I'm double-checking that now).
> 
> Expanding this - I've got a confirmation from Octavia engineers that check for v2.24 should be safe. Nevertheless I'd also like to add a proper error handling for healthmonitor creation, so that NotImplementedError [1] will not be a fatal error for us.
> 
> [1] https://opendev.org/openstack/octavia-lib/src/branch/master/octavia_lib/api/drivers/provider_base.py#L319-L323

And another point of view. So checking API versions will only work if ovn-octavia-provider is in the same version and it doesn't need to be. I was told it's best to rely on reacting on NotImplementedError. That's 501 error code returned from API.

**Comment by ching-kuo** [comment]
@dulek 
I'm currently checking if the error string contains 501 to see if health monitor is enabled. It is possible to get the status code and check it here [1] if we don't do `Extract()` directly, but we still need to handle it here [2].

[1] https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/pkg/clients/loadbalancer.go#L222
[2] https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/pkg/cloud/services/loadbalancer/loadbalancer.go#L358

File: pkg/cloud/services/loadbalancer/loadbalancer.go [hunk 4]
```diff
@@ -64,13 +64,14 @@ func (s *Service) ReconcileLoadBalancer(openStackCluster *infrav1.OpenStackClust
...
+	// Choose the selected provider if it is set in cluster spec, if not, omit the field and Octavia will use the default provider.
+	lbProvider := ""
+	if openStackCluster.Spec.APIServerLoadBalancer.Provider != "" {
+		for _, v := range providers {
+			if v.Name == openStackCluster.Spec.APIServerLoadBalancer.Provider {
+				lbProvider = v.Name
+				break
+			}
 		}
 	}
```
Comment (dulek) [inline pkg/cloud/services/loadbalancer/loadbalancer.go:76]: We should log a warning for the user that selected Octavia provider doesn't exist and that we'll skip setting it. Failing silently is never a good idea. Let's also make sure to create an event on the Service we're handling here.

File: pkg/cloud/services/loadbalancer/loadbalancer.go [hunk 5]
```diff
@@ -356,6 +363,12 @@ func (s *Service) getOrCreateMonitor(openStackCluster *infrav1.OpenStackCluster,
 		Timeout:        5,
 	}
 	monitor, err = s.loadbalancerClient.CreateMonitor(monitorCreateOpts)
+	// Skip creating monitor if it is not supported by Octavia provider
+	if strings.Contains(err.Error(), "501") {
```
Comment (dulek) [inline pkg/cloud/services/loadbalancer/loadbalancer.go:367]: I think a proper check would be something like here [1]. I see there's no `ErrDefault501`, but you should be able to convert to `ErrUnexpectedResponseCode` and then do the check?

[1] https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/8e4cf26f716ed50abd9d3efc74d0297dfba633ae/pkg/utils/errors/errors.go#L58-L72

File: pkg/cloud/services/loadbalancer/loadbalancer.go [hunk 6]
```diff
@@ -356,6 +363,12 @@ func (s *Service) getOrCreateMonitor(openStackCluster *infrav1.OpenStackCluster,
...
+		record.Warnf(openStackCluster, "SkippedCreateMonitor", "Health Monitor is not implemented with the current provider")
```
Comment (dulek) [inline pkg/cloud/services/loadbalancer/loadbalancer.go:368]: We should probably add an even explaining this too.

**Review by dulek — CHANGES_REQUESTED** [review]

File: pkg/cloud/services/loadbalancer/loadbalancer.go (hunk 5 above)
Comment (ching-kuo) [reply pkg/cloud/services/loadbalancer/loadbalancer.go]: Added the conversion, check if the status code is `501` record the warning and event.

File: pkg/cloud/services/loadbalancer/loadbalancer.go (hunk 6 above)
Comment (ching-kuo) [reply pkg/cloud/services/loadbalancer/loadbalancer.go]: Added event.

File: pkg/cloud/services/loadbalancer/loadbalancer.go [hunk 7]
```diff
@@ -356,6 +368,16 @@ func (s *Service) getOrCreateMonitor(openStackCluster *infrav1.OpenStackCluster,
...
 	monitor, err = s.loadbalancerClient.CreateMonitor(monitorCreateOpts)
+	// Skip creating monitor if it is not supported by Octavia provider
+	var errUnexpectedResponseCode gophercloud.ErrUnexpectedResponseCode
+	if errors.As(err, &errUnexpectedResponseCode) {
+		if errUnexpectedResponseCode.Actual == http.StatusNotImplemented {
+			record.Warnf(openStackCluster, "SkippedCreateMonitor", "Health Monitor is not implemented with the current provider.")
+			record.Eventf(openStackCluster, "SkippedCreateMonitor", "Health Monitor is not created as it's not implemented with the current provider.")
+			return nil
+		}
+	}
```
Comment (dulek) [inline pkg/cloud/services/loadbalancer/loadbalancer.go:379]: Looks pretty good. I can suggest to move this to utils/errors/errors.go as `IsNotImplementedError()` to skip some logic here.

**Comment by dulek** [comment]
Besides a tiny code placement remark this looks good to me!

File: pkg/cloud/services/loadbalancer/loadbalancer.go (hunk 7 above)
Comment (ching-kuo) [reply pkg/cloud/services/loadbalancer/loadbalancer.go]: Fixed

**Comment by jichenjc** [comment]
the follow up question is whether we want to test in the gate ... seems reasonable to CI test the change about OVN provider

**Comment by ching-kuo** [comment]
I'm not sure how popular is OVN LB used in OpenStack, I can check how the gate tests works and see if I can contribute to test changes regarding OVN provider.

e2e test seems to be broken from the logs. I don't think the issue is related to my changes.

**Comment by ching-kuo** [comment]
@dulek Anything else that needs to be fixed?

File: pkg/cloud/services/loadbalancer/loadbalancer.go [hunk 8]
```diff
@@ -64,13 +63,18 @@ func (s *Service) ReconcileLoadBalancer(openStackCluster *infrav1.OpenStackClust
...
+	if openStackCluster.Spec.APIServerLoadBalancer.Provider != "" {
+		for _, v := range providers {
+			if v.Name == openStackCluster.Spec.APIServerLoadBalancer.Provider {
+				lbProvider = v.Name
+				break
+			}
+		}
+		if lbProvider == "" {
+			record.Warnf(openStackCluster, "OctaviaProviderNotFound", "Provider specified for Octavia not found.")
+			record.Eventf(openStackCluster, "OctaviaProviderNotFound", "Provider specified for Octaiva not found, using the default provider.")
```
Comment (dulek) [inline pkg/cloud/services/loadbalancer/loadbalancer.go:77]: There's an "Octaiva" typo.

Comment (dulek) [reply pkg/cloud/services/loadbalancer/loadbalancer.go:77]: Also now looking at this closer, I think I'd include the information about which provider is missing:

`"Provider %s specified for API LB not found, using the default Octavia provider.", openStackCluster.Spec.APIServerLoadBalancer.Provider`

File: pkg/cloud/services/loadbalancer/loadbalancer.go [hunk 9]
```diff
@@ -356,6 +366,13 @@ func (s *Service) getOrCreateMonitor(openStackCluster *infrav1.OpenStackCluster,
 		Timeout:        5,
 	}
 	monitor, err = s.loadbalancerClient.CreateMonitor(monitorCreateOpts)
+	// Skip creating monitor if it is not supported by Octavia provider
+	if capoerrors.IsNotImplementedError(err) {
+		record.Warnf(openStackCluster, "SkippedCreateMonitor", "Health Monitor is not implemented with the current provider.")
```
Comment (dulek) [inline pkg/cloud/services/loadbalancer/loadbalancer.go:371]: `"Health monitors are not supported with the current Octavia provider"` would sound a tiny bit better, second message can be updated in a similar fashion.

**Review by dulek — APPROVED** [review]
It's fine, just tiny phrasing comments to include if you'll need to update the patch.

**Comment by dulek** [comment]
@jichenjc: Any idea where the `do-not-merge/hold` label comes from? I don't want to remove it without permission.

**Comment by dulek** [comment]
Oh, it's from the initial PR message. So @ching-kuo, you can remove it whenever you're ready.

**Comment by ching-kuo** [comment]
@dulek, I've rebased and fixed some test in conversion. Can you review the patch again? Thank you.

**Comment by dulek** [comment]
You could have fixed the typo and messages too, but this can be done as a follow up.
/lgtm

**Comment by ching-kuo** [comment]
@dulek 
Sorry, I missed your latest review, fixed the messages and typo.

File: pkg/cloud/services/loadbalancer/loadbalancer.go [hunk 10]
```diff
@@ -356,6 +366,13 @@ func (s *Service) getOrCreateMonitor(openStackCluster *infrav1.OpenStackCluster,
 		Timeout:        5,
 	}
 	monitor, err = s.loadbalancerClient.CreateMonitor(monitorCreateOpts)
+	// Skip creating monitor if it is not supported by Octavia provider
+	if capoerrors.IsNotImplementedError(err) {
+		record.Warnf(openStackCluster, "SkippedCreateMonitor", "Health monitors are not supported with the current Octavia provider.")
+		record.Eventf(openStackCluster, "SkippedCreateMonitor", "Health Monitor is not created as it's not implemented with the current provider.")
```
Comment (dulek) [inline pkg/cloud/services/loadbalancer/loadbalancer.go:372]: This message should be updated in a similar fashion as it's user-facing. I added "Octavia" on purpose, to avoid confusion what "provider" means here. An inexperienced user may think that we're saying cluster-api-*provider*-openstack doesn't support health monitors.

**Comment by Jeremy-Boyle** [comment]
Thanks for fixing this, waiting for release!
